### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#109]
Related to #86: 

Maybe an idea is to split this package into `landscapemetrics` and e.g. `landscapemetrics.engine`. 

We could move all "core" functions (i.e. calculating metrics) to the core package and importing it in `landscapemetrics`. This would give exactly the same functionality as now for `landscapemetrics` and users would experience no difference (including all plotting/sampling etc. functions). Thereby, we still have this really nice tool for everything related to landscape metrics. 

However, if somebody just wants to calculate some metrics straightforward as possible with less dependencies (e.g. on a HPC), it would be sufficient to only load `landscapemetrics.engine`

As example, `spatstat` does something similar and the package actually loads e.g. `spatstat.utils` and `spatstat.data`

**Comment by Nowosad** [comment]
I cannot find our previous discussion on this topic, but I am in favour of going that.

**Comment by mhesselbarth** [comment]
Yeah, not really sure in which issue we acutally talked about this...

**Comment by mhesselbarth** [comment]
I started a new GitHub repo (https://github.com/r-spatialecology/landscapemetrics.engine) the other day and already put some stuff there

**Comment by mhesselbarth** [comment]
Not sure anymore if this is really needed. Please reopen if you want to further discuss though
