### ISSUE TITLE
FAQ vignette

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapemetrics#112]
Does a FAQ vignette makes sense?

Collect common themes from previous issues here and highlight hidden functionality (like `to_disk`)

**Comment by mhesselbarth** [comment]
Doesn't hurt 👍

**Comment by bitbacchus** [comment]
Sure, good idea!

**Comment by mhesselbarth** [comment]
Parallel computing #87

**Comment by mhesselbarth** [comment]
How to extract only RasterLayer for e.g. window_lsm, sample_lsm, etc
