### ISSUE TITLE
Error using sample_lsm()

### ISSUE THREAD

**Issue by vjjan91** [r-spatialecology/landscapemetrics#118]
Currently trying to calculate the class-level metrics for a given raster within a 1km buffer.

Code: 
land_1km <- sample_lsm(lc2018, y = pointsLsm, shape = "circle", size = 1000,
                    level="class")

I am getting this error: Error in .local(obj, ...) : NA values in coordinates

Help?

**Comment by mhesselbarth** [comment]
Hey, 
Could you please provide the data so we can reproduce the error?

**Comment by vjjan91** [comment]
Here's the raster - https://www.dropbox.com/sh/eqdvh0cjrabma10/AABQrcQtuNeIBY43-c91ZiW6a?dl=0

Please let me know once you use the same.

**Comment by vjjan91** [comment]
The pointsLSM used above are: 

coordinates(pointsLsm)
             X       Y
 [1,] 702732.0 1264140
 [2,] 702740.0 1264317
 [3,] 704278.5 1264938
 [4,] 704475.3 1264887
 [5,] 704686.6 1264835
 [6,] 718493.4 1145769
 [7,] 718324.6 1145621
 [8,] 718326.0 1145388
 [9,] 718346.8 1144981
[10,] 718352.3 1144686
[11,] 718578.9 1144951

**Comment by vjjan91** [comment]
This is weird! I tried the same function today and it worked on the raster. The only thing I did differently was not truncating the data range on the raster:

ie. lc2018[lc2018 < 1 | lc2018 > 7] <- NA

**Comment by vjjan91** [comment]
I figured out the error. There were NaN values for the pointsLsm object. Thank you for offering to take a look!
