### ISSUE TITLE
new argument for calculate_lsm

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapemetrics#119]
We should introduce a new argument to calculate_lsm, that has several options based in the literature of landscape metrics. These options each store a selection a review made of meaningful metrics, see for example:

- Cushman, S.A., McGarigal, K. & Neel, M.C. (2008). Parsimony in landscape metrics: Strength, universality, and consistency. Ecological Indicators, 8, 691–703.
- https://global.oup.com/academic/product/essentials-of-landscape-ecology-9780198838388?cc=de&lang=en&

This would make it easier for inexperienced users to not aimlessly calculate every metric there is.

**Comment by mhesselbarth** [comment]
I like the idea, but the best place would be to add this to `list_lsm()`. `calculate_lsm()` simply class that anyways. 

The easiest would be to all e.g. "chushman" was `what`-argument.

**Comment by Nowosad** [comment]
I would not go this way. I haven't read the "Essentials..." book yet, but I know the Cushman et al. paper. It uses some example regions and analyses them using principal components analysis, clustering, and discriminant analysis. While it is useful, I would think it is not universal for each dataset or scale. 

In the same time, I think it could be a good idea to create a vignette with a sample calculation of those metrics. There could be a list of them, that every user could copy and paste to their code...
