### ISSUE TITLE
Export headers in inst/include

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#120]
Hi all,
I am now working on a different package that in its c++ functions uses some c++ code from landscapemetrics (e.g. rcpp_get_coocurrence_matrix). Right now, for the development purposes, I just copied the .cpp files to the new package, but probably the better way is to expose the landscapemetrics cpp headers in inst/include.

What do you think about that?
Of course, there are two possibilities here:
1. Just expose the landscapemetrics cpp headers in inst/include, or:
2. Create a new package (landscapeengine) with cpp code and exposed headers.

**Comment by mhesselbarth** [comment]
Related to #109:

As discussed in #109, I will split the landscapemetrics package in the nearear future into landscapemetrics.engine (including all metrics and building blocks and thereby the Rcpp stuff) and landscapemetrics (including all sampling and visualization functions and importing lsm.engine).

**Comment by Nowosad** [comment]
The answers here can be useful for this case - https://twitter.com/jakub_nowosad/status/1140969799062888448.
