### ISSUE TITLE
issue with sample_lsm

### ISSUE THREAD

**Issue by croeland** [r-spatialecology/landscapemetrics#122]
I am trying to calculate the amount of aspen size class around sample points. I have run the below code multiple times before with no issues but now I am getting this error message, even when I go back and run code that had previously worked. 

OL_aspen_size<-raster("LO_WFIRS_18_1000AspenSize.tif")
cp_2018<-st_read("2018_capture_males.shp", quiet=TRUE)

cp2018_50_aspen_size<-sample_lsm(OL_aspen_size,points = cp_2018 ,size = 50, what = "lsm_c_ca", shape = "circle") 

Error in lapply(X = raster::as.list(landscape), FUN = sample_lsm_int,  : 
                  argument "y" is missing, with no default

**Comment by mhesselbarth** [comment]
Hey there, 

We changed the name of the `points` argument to `y` to be consistent among all functions. Seems like, we forgot to write that in the NEWS. Sorry about that. 

The following code should work just as before:
```
OL_aspen_size<-raster("LO_WFIRS_18_1000AspenSize.tif")
cp_2018<-st_read("2018_capture_males.shp", quiet=TRUE)

cp2018_50_aspen_size<-sample_lsm(OL_aspen_size,y = cp_2018 ,size = 50, what = "lsm_c_ca", shape = "circle")
```

**Comment by croeland** [comment]
Thanks for the reply,

Now I am getting a different error message....

Error: 'y' must be a matrix, SpatialPoints, SpatialLines or SpatialPolygons.

Not sure if it is something I am doing wrong or not. Thanks for the help.

**Comment by croeland** [comment]
To give a little more detail on what is going on and to make sure it wasn't something wrong with my data, I followed the example on https://www.r-bloggers.com/efficient-landscape-metrics-calculations-for-buffers-around-sampling-points/amp/. Even when doing this and changing points to "y" I still got the same error message:

Error: 'y' must be a matrix, SpatialPoints, SpatialLines or SpatialPolygons.

**Comment by mhesselbarth** [comment]
Okay...seems like therre is a problem with your sample points (wrong data format?) 

If you can provide the data (either here or via e-mail), I can have a deeper look into it.

**Comment by croeland** [comment]
Here they are. I really appreciate you taking a look at them. 
[cp_2018.zip](https://github.com/r-spatialecology/landscapemetrics/files/3377409/cp_2018.zip)

**Comment by Nowosad** [comment]
@mhesselbarth I checked my [blog post](https://nowosad.github.io/post/lsm-bp1/) - It seems that I used an sf object as the second argument there. However, right now an sf object as a second argument returns an error. Do you know why?

**Comment by mhesselbarth** [comment]
@marcosci (who is on holidays at the moment) did the sf objects so I don't know right away what the problem could be. I will have a look today or tomorrow.

**Comment by mhesselbarth** [comment]
@croeland You can install the development version using `devtools::install_github("r-spatialecology/landscapemetrics")` and everything should work now. Alternatively, you can convert your `sf` object to a `sp` object using e.g. `as(cp_2018, 'Spatial')`. Both ways return in the same result. 

@Nowosad `sample_lsm()` didn't support `sf` objects and I don't know why because I'm quite sure it did at some point. Not sure why and when we removed that? Anyways, should work now again with `sf`.

**Comment by croeland** [comment]
@mhesselbarth Thank you for your help. This package has been a great tool so far for me while working on my thesis.

**Comment by Nowosad** [comment]
Thanks @mhesselbarth !
