### ISSUE TITLE
export results

### ISSUE THREAD

**Issue by JonHak** [r-spatialecology/landscapemetrics#129]
I've used Fragstatats and SDMTools a fair amount and I wanted to try out landscapemetrics.  I've worked through most of the tutorial for landscapemetrics, but the one thing I can't seem to find is how to get my results out in a spatial dataset for use in GIS.  The show_patches(landscape)  gives a nice graphic of the patches, but I would like to export that type of product out as a raster and none of the ways I've tried work.   I'm not a novice in R, but I'm also no expert so any help would greatly appreciated.

**Comment by mhesselbarth** [comment]
Good to hear you give `landscapemetrics` a try! I think you are looking for the `spatialize_lsm()` function, which basically returns the visual output of  `show_patches()` as a RasterLayer. Then, you can simply write this RasterLayer (or list of RasterLayers) to an e.g. TIF-file that should be readable by most GIS-software (I'm not a GIS expert though).

``` r
library(landscapemetrics)
library(raster)
#> Loading required package: sp

patch_area <- spatialize_lsm(landscape, 
                             what = "lsm_p_area")
#> Warning: Please use check_landscape() to ensure the input data is valid.

# output will always be a list to be type stable for RasterStacks
writeRaster(x = patch_area[[1]]$lsm_p_area, 
            filename = "/Users/Maximilian/Desktop/patch_area.tif")
```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JonHak** [comment]
Maximilian, 
Thanks!! That did exactly what I wanted, the writeRaster syntax I have used before was a bit off from what your example showed.  

Thanks again 
Jon

**Comment by mhesselbarth** [comment]
Great! 

I  will close this issue for now. Feel free to re-open at any time if a related/follow up question comes up
