### ISSUE TITLE
incorrect description and question

### ISSUE THREAD

**Issue by chrhauser** [r-spatialecology/landscapemetrics#135]
Thanks a lot for programming the landscape metrics package, I am just starting out working with these types of metrics and your package facilitates my life a lot!

First one observation: On page 199 of the documentation you provide the description for lsm_l_shape_cv as "Covariance of variation shape index". If I am not mistaken this should read "Coefficient of variation shape index"?

I am trying to compute various shape indices at the landscape level for a raster file. Can I also find the area-weighted mean shape index distribution (SHAPE_AM) and the median shape index distribution (SHAPE_MD) in your package? Or is there a possibility to compute these based on the shape indices provided in the LSM package? Sorry for these basic questions, any feedback would be greatly appreciated!

**Comment by mhesselbarth** [comment]
Hey there, 

I'm glad to hear the package helps you! 

Thanks for pointing out the typo. Yes, it should be "Coefficient of variation shape index". We will fix that for the newest release. 

Currently, we don't have any weighted means. But that might be something we tackle in the future. Until then, it shouldn't be too hard to calculate it yourself with the functionality of the package that is already there. Please see the following code. If I'm not mistaken, this should give you the weighted mean of the shape index,

``` r
library(landscapemetrics)
library(dplyr)

# calculate shape index of each patch
shape_patch <- lsm_p_shape(landscape)

# calculate area of each patch
area_patch <- lsm_p_area(landscape)

# join shape and area of each patch
# multiply each shape with the area for weighting
# divide sum of weighted shape by sum of weights (area)
shape_am <- left_join(x = shape_patch, y = area_patch, 
                      by = c("layer", "level", "class", "id")) %>% 
    dplyr::mutate(value.w = value.x * value.y) %>% 
    dplyr::summarise(value.am = sum(value.w) / sum(value.y))

# calculate median of all patches
shape_md <- median(shape_patch$value)
```

<sup>Created on 2019-10-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by chrhauser** [comment]
Thanks a lot for the response and the code! That was tremendously helpful!!

I have another very difficult nut to crack before I can implement the metrics in your package. Basically I would like to compute the landscape metrics for a clipped version of the Corine landcover raster data with a resolution of 100 meters. I have another dataset containing counts of social media data for the same area but with a resolution of 1000 meters. So basically for each raster cell of the social media data I want to compute a selection of landscape metrics for the corrisponding 100 cells of the Corine Landcover data. The final result should be a dataset that contains the number of social meda data for each 1 km cell and the corresponding results for the landscape metrics in this area. I am still somewhat at a loss how I can do the computations in the Corine Landcover data based on the extent of the cells in the social media raster data.

I know this question is related only indirectly to the application of your package, still any help in this regard would be greatly appreciated!

[Clips.zip](https://github.com/r-spatialecology/landscapemetrics/files/3803150/Clips.zip)

**Comment by mhesselbarth** [comment]
Mmh...I am not 100% sure how to solve that. Maybe `spatialize_lsm()` could help you. The function returns you a RasterLayer in which each cell has the corresponding value of the patch level metric. Maybe, then you could use this and and `raster::extract` to get the values at the cell locations of your other RasterLayer. Probably, you need to convert it to sp points or something similar first, but that shouldn't be a big problem.

**Comment by mhesselbarth** [comment]
I will close the issue for now.

Please reopen if needed.
