### ISSUE TITLE
rstudio::conf(2020L) Hex Wall 

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#139]
Hi @mhesselbarth, maybe it would be nice to submit the package logo to https://docs.google.com/forms/d/e/1FAIpQLSdaLWrD1YWLVMkY7-Lw0YGUqJBpi_n4ZD39BxCIUzq2Kr-v9g/viewform. What do you think?

**Comment by mhesselbarth** [comment]
Sure thing! I can submit it today.

**Comment by mhesselbarth** [comment]
Done. Thanks for pointing out.
