### ISSUE TITLE
Delete branches

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#141]
Over the time, we colleccted some branches and I'm not sure if we still need all of them. 

I think we can delete the following: 
- updates-ent (should be merged to master d10ae973354015dbecd435fd28e3cda41d6dd11d)
- cleaner_cpp (should be merged to master 219310af50d509b42874135a6a4069bd8221cfc0)

Not sure about the following:
- it (No idea what this is)
- future_apply (I think we all agreed to not include inbuild parallelization, correct? So delete?)
- rcpp_parallell (I think we all agreed to not include inbuild parallelization, correct? So delete?)

**Comment by bitbacchus** [comment]
I agree

**Comment by Nowosad** [comment]
@mhesselbarth Feel free to remove `it`.

**Comment by Nowosad** [comment]
@mhesselbarth Also - remove `updates-ent`

**Comment by Nowosad** [comment]
@mhesselbarth Also - remove `cleaner_cpp`.

**Comment by bitbacchus** [comment]
Hm, I re-read #108, and I think we had agreed that it would be beneficial to have optional built-in parallelization for large rasters. So, maybe don't delete rcpp_parallel just yet :-)

**Comment by mhesselbarth** [comment]
Done.
