### ISSUE TITLE
Differences between README and the main webpage

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#142]
Compare https://github.com/r-spatialecology/landscapemetrics and https://r-spatialecology.github.io/landscapemetrics/.

Differences:
1. Citation
2. Example table

**Comment by mhesselbarth** [comment]
I fixed the table, but have no idea why that stupid line break is added in the citation

**Comment by mhesselbarth** [comment]
The HTML seemed to do the trick, good job @Nowosad

**Comment by mhesselbarth** [comment]
Okay....should be finally fixed... 9c8e3b112f553fe20cc413ad095a928c5fcff6e4

Didn't know there is an preview possible. Sorry for the billion pushes :)
