### ISSUE TITLE
Check class of landscape

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#147]
I got the following mail: 

> [...]
> Apparently your package no longer works correctly when
class(matrix(...)) gives a vector of length two and conditions of length
greater than one in 'if' or 'while' give an error: please fix as
necessary.
>
> See
<https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html>
for more information about correctly using class() in package code.
>
>Please correct before 2019-12-18 to safely retain your package on CRAN.
> [...]

**Comment by Nowosad** [comment]
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/landscapemetrics-00check.html

**Comment by Nowosad** [comment]
We cannot use `class(landscape) != "matrix"` any more (https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/index.html).

**Comment by mhesselbarth** [comment]
I will push in a few minutes

**Comment by Nowosad** [comment]
We probably should use `!inherits(landscape, "matrix")`

**Comment by mhesselbarth** [comment]
I went for `!is(landscape, "matrix")` which should be the same. 

I'm just running some checks at the moment if everything runs smoothly.

**Comment by mhesselbarth** [comment]
Fixed: 3dcc29cda049cc0cf38d45ab93a82d54d2f575f8

**Comment by mhesselbarth** [comment]
Okay....I had some problems with my local git and needed to rebase.

Should be fixed now: 2ad24f886c7bc33c3c3df674d7b5696e6d308f78, 6c0cb8a1d0534097a232d080df7ae5d48c7b59d7
