### ISSUE TITLE
Landscape distribution statistics

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#168]
I got quite a few questions about the area-weighted mean. 

I'm working on a vignette that shows how to calculate it at the moment.

**Comment by mhesselbarth** [comment]
cc8b91bf04d7130f69c0f7a93a27c75f866a7ef2

Please feel free to modify the vignette if you want to.

**Comment by Nowosad** [comment]
Awesome!

**Comment by Nowosad** [comment]
@mhesselbarth - one idea - maybe you could start with one example on how to calculate one of the implemented measures  (_mn, _cv, _sd)?

**Comment by mhesselbarth** [comment]
bc1de0a8d0c71fad76a1e6d3c549349af493810d
