### ISSUE TITLE
calculate_lsm not working

### ISSUE THREAD

**Issue by gazzapol** [r-spatialecology/landscapemetrics#171]
Hello, 
the function calculate_lsm is currently producing an error:

```
Error in list_lsm(level = level, metric = metric, name = name, type = type,  : 
  object 'lsm_abbreviations_names' not found
```

the code:

```r
landscapemetrics::calculate_lsm(landscape=landscapemetrics::augusta_nlcd, level = c("class", "landscape"), type = "aggregation metric")
```

**Comment by mhesselbarth** [comment]
Could you please share your `sessionInfo()` with me. On my computer, your code is working and I can't reproduce your error.

**Comment by gazzapol** [comment]
> landscapemetrics::calculate_lsm(landscape=landscapemetrics::augusta_nlcd, level = c("class", "landscape"), type = "aggregation metric")
Error in list_lsm(level = level, metric = metric, name = name, type = type,  : 
  object 'lsm_abbreviations_names' not found
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.1       assertthat_0.2.0     cli_1.1.0           
 [4] pillar_1.3.1         sp_1.2-7             tibble_2.0.1        
 [7] crayon_1.3.4         Rcpp_1.0.3           raster_2.8-19       
[10] codetools_0.2-15     grid_3.4.1           pkgconfig_2.0.2     
[13] rlang_0.4.0          landscapemetrics_1.1 lattice_0.20-35     
>

**Comment by mhesselbarth** [comment]
Could you please update the `landscapemetrics` package (current CRAN version is v1.4.3) and see if you still get the same error?

**Comment by gazzapol** [comment]
![image](https://user-images.githubusercontent.com/31890270/78797840-8d501300-79b8-11ea-8ee7-218d669b3bb5.png)
 it automatically installs the binary v.1.1

**Comment by Nowosad** [comment]
@gazzapol you need to update your R version first. The current R is 3.6.3 and you have R 3.4.1, which is almost three years old.

**Comment by gazzapol** [comment]
@mhesselbarth 1. it automatically installs v.1.1 (see above). 2. when choosing version 1.4.3. the problem persits. 
> install.packages("landscapemetrics", type="source")
Installing package into ‘C:/Users/gazza_000/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.csiro.au/src/contrib/landscapemetrics_1.4.3.tar.gz'
Content type 'application/x-gzip' length 724726 bytes (707 KB)
downloaded 707 KB

* installing *source* package 'landscapemetrics' ...
** package 'landscapemetrics' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="landscapemetrics.dll" OBJECTS="RcppExports.o rcpp_cclabel.o rcpp_create_neighborhood.o rcpp_get_boundaries.o rcpp_get_circle.o rcpp_get_class_index_map.o rcpp_get_composition_vector.o rcpp_get_coocurrence_matrix.o rcpp_get_coocurrence_matrix_diag.o rcpp_get_coocurrence_vector.o rcpp_get_entropy.o rcpp_get_nearest_neighbor.o rcpp_get_unique_values.o rcpp_smallest_circle.o"' had status 127
ERROR: compilation failed for package 'landscapemetrics'
* removing 'C:/Users/gazza_000/Documents/R/win-library/3.4/landscapemetrics'

The downloaded source packages are in
        ‘C:\Users\gazza_000\AppData\Local\Temp\RtmpYZUAxM\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\gazza_000\Documents\R\win-library\3.4" C:\Users\GAZZA_~1\AppData\Local\Temp\RtmpYZUAxM/downloaded_packages/landscapemetrics_1.4.3.tar.gz' had status 1 
2: In install.packages("landscapemetrics", type = "source") :
  installation of package ‘landscapemetrics’ had non-zero exit status
> landscapemetrics::calculate_lsm(landscape=landscapemetrics::augusta_nlcd, level = c("class", "landscape"), type = "aggregation metric")
Error in loadNamespace(name) : 
  there is no package called ‘landscapemetrics’

**Comment by gazzapol** [comment]
@mhesselbarth source v. 1.4.3 do not produce the error (which binary v.1.1 actually does). @Nowosad the installed R version is not the problem here (I did not update the R version meanwhile). Maybe is a bug in the 1.1 version? Still, R atutomatically installs the 1.1 version, unless "source" is specified.

**Comment by Nowosad** [comment]
@gazzapol It is possible that there was a bug in the 1.1 version. However the bug was fixed and does not exist in 1.4.3. 

The installed R version is a problem here - binaries version changes with R versions. Therefore, with R 3.6.3 you will have also the binary version of landscapemetrics 1.4.3.

**Comment by gazzapol** [comment]
@Nowosad Oh I did not know that, thanks for the hint.

**Comment by Nowosad** [comment]
:+1:
