### ISSUE TITLE
Problem with class and id features after conversion from KML to raster. 

### ISSUE THREAD

**Issue by rickcleong** [r-spatialecology/landscapemetrics#176]
Hello there,

First and foremost, thank you so much to the creators for creating this package. I have tried out Fragstats several times but it is not very user-friendly (in my opinion). Anyway, I have a question which is linked to the input of the raster into the functions of landscape metrics. 

I am comparing patch statistics of 10 reef patches of the same type (same class). I obtained the polygons of the patches in KML, saved them as polygons and imported into spatial polygon into UTM, followed by a raster with the coding below: 
`utm_crs <-  c("+proj=utm +datum=WGS84 +zone=56H +south=T +no_defs +ellps=WGS84 +towgs84=0,0,0") `
`CrookhavenOysters<-readOGR("CrookhavenOysters_1.kml")` 
`Crookhavenreefs<- spTransform(CrookhavenOysters, utm_crs)` 
`CR_rast <- raster(extent(Crookhavenreefs), res = 0.05, crs = utm_crs) `
`Crookhaven_rast<- rasterize(Crookhavenreefs, CR_rast,update=TRUE) `

There is no issue with obtaining the raster but when I checked with the 'check_landscape' function, it appears that my unique patch ids appeared as unique classes. 

`check_landscape(Crookhaven_rast, verbose = TRUE) `

 layer       crs     units   class n_classes OK
1     1 projected +proj=utm integer        10  

Just to confirm that the error has indeed occurred at these features, i ran the class-type, edge density calculation function at class level i.e. `lsm_c_ed(Crookhaven_rast, directions =8)` and problem does occur at the raster level.

layer level class    id metric value 
   <int> <chr> <int> <int> <chr>  <dbl>
 1     1 class     1    NA ed         0
 2     1 class     2    NA ed         0
 3     1 class     3    NA ed         0
 4     1 class     4    NA ed         0
 5     1 class     5    NA ed         0
 6     1 class     6    NA ed         0
 7     1 class     7    NA ed         0
 8     1 class     8    NA ed         0
 9     1 class     9    NA ed         0
10     1 class    10    NA ed         0

By any chance, if anyone knows how to deal with this issue? I understand this issue might be at the creation of the raster, which I am not most familiar with, and not directly related to the functions in landscape metrics.

I am also not sure about other technical features (which might be missing) in a raster to look out for, apart from the aforementioned ones in CRAN PDF file. Perhaps if there is an additional function to verify, unique patch IDs in the 'check landscape' function, that might help to troubleshoot issues when performing the functions in the package.

I will appreciate any help related to my issue. Thank you in advance.

p/S: On another note, just a small question, by any chance that the proximity and similar index calculations have been developed at class and landscape levels? 

Cheers,

Rick Leong

**Comment by mhesselbarth** [comment]
Hey Rick, 

Yeah, it seems like there is an issue when you create the raster. Did you already try to plot it? Does it look correct? 

It's hard to help without having the data, but did you try to set the `field` argument of the `rasterize()` function? From the help file, this sounds bit like it could solve your problem.

It would be helpful if you could share your data, so I can reproduce the problem.

**Comment by rickcleong** [comment]
Hi @mhesselbarth ,

Thanks for your quick reply and congrats on your PhD graduation (just saw on your Twitter)! :) 

I actually did try to set to `field ` but there was nothing. Here's the KML file in the Zip file and the attached  R plot, showing different colors of different class integers for each patch. 

![plot_CR_raster](https://user-images.githubusercontent.com/64528539/80595665-77d68200-8a68-11ea-970d-e56fd5921489.jpeg)
[CrookhavenOysters_1.zip](https://github.com/r-spatialecology/landscapemetrics/files/4551595/CrookhavenOysters_1.zip)
![plot_CR_raster](https://user-images.githubusercontent.com/64528539/80595735-95a3e700-8a68-11ea-9917-15109c5c6abb.jpeg)

Thank you very much and good evening from Sydney :)

Cheers,

Rick :)

**Comment by mhesselbarth** [comment]
Oh...now I see the "problem". Well, it's not directly a problem. The edge is defined as "all edges between class i and all other classes k". However, the cells between your patches are NA (no value)...following no edge is calculated. You have a few options. 

The first one would be to calculate the perimeter of all patches, group it by class and sum the results. 

The second option would be to reclassify all NA values as e.g. class 99, calculate the edge and remove class 99 from the results.

However, there is some stuff you need to consider. All edge functions have the argument `count_boundary` which specifies if edges to the total landscape boundary should be included as well. If you set this to `TRUE` results between the two option will be the same. If you set it to `FALSE` the edge length will be slightly shorter for option two because of the patches that are located directly at the landscape boundary.

If you want to calculate the edge density, it is important to keep in mind, that the total area is calculated based on all cells that are not NA. So in the case of the first option, you would get a much higher edge density because the total landscape is smaller. In case you understand the total extent (including the NAs between the patches) as part of the landscape you would need to chose the second option and reclassify NAs as class 99. Then you can simply divide the total edge by the landscape area.

I hope that clarifies everything. Here is some code to show what I mean:


``` r
library(dplyr)
library(raster)
library(landscapemetrics)
library(rgdal)
library(sp)

utm_crs <- c("+proj=utm +datum=WGS84 +zone=56H +south=T +no_defs +ellps=WGS84 +towgs84=0,0,0") 
CrookhavenOysters <- readOGR("~/Desktop/CrookhavenOysters.kml")
Crookhavenreefs <- spTransform(CrookhavenOysters, utm_crs)
CR_rast <- raster(extent(Crookhavenreefs), res = 0.05, crs = utm_crs) 
Crookhaven_rast <- rasterize(Crookhavenreefs, CR_rast,update=TRUE)

check_landscape(Crookhaven_rast)
#>   layer       crs     units   class n_classes OK
#> 1     1 projected +proj=utm integer        10  ✓

# sum perimeter of all patches grouped by class
summed_perim <- landscapemetrics::lsm_p_perim(Crookhaven_rast) %>% 
  dplyr::group_by(class) %>% 
  dplyr::summarise(value = sum(value))

# reclassify all NA to 99
Crookhaven_rast_reclass <- Crookhaven_rast
Crookhaven_rast_reclass[is.na(raster::values(Crookhaven_rast_reclass))] <- 99

total_edge <- landscapemetrics::lsm_c_te(Crookhaven_rast_reclass, 
                                         count_boundary = TRUE) %>% 
  dplyr::filter(class != 99)

# should be the same...
summed_perim
#> # A tibble: 10 x 2
#>    class value
#>    <int> <dbl>
#>  1     1  61.8
#>  2     2  45.8
#>  3     3  11.2
#>  4     4  20.9
#>  5     5  20.9
#>  6     6 521. 
#>  7     7  60.7
#>  8     8  69.3
#>  9     9 116. 
#> 10    10 111.
total_edge
#> # A tibble: 10 x 6
#>    layer level class    id metric value
#>    <int> <chr> <int> <int> <chr>  <dbl>
#>  1     1 class     1    NA te      61.8
#>  2     1 class     2    NA te      45.8
#>  3     1 class     3    NA te      11.2
#>  4     1 class     4    NA te      20.9
#>  5     1 class     5    NA te      20.9
#>  6     1 class     6    NA te     521. 
#>  7     1 class     7    NA te      60.7
#>  8     1 class     8    NA te      69.3
#>  9     1 class     9    NA te     116. 
#> 10     1 class    10    NA te     111.

# total area to calculate edge density
landscapemetrics::lsm_l_ta(Crookhaven_rast)
#> # A tibble: 1 x 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA ta     0.355
landscapemetrics::lsm_l_ta(Crookhaven_rast_reclass)
#> # A tibble: 1 x 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA ta      3.20
```

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rickcleong** [comment]
Hi @mhesselbarth Max,

Really appreciate your reply with the corrected codes to measure the edge density. Thank you very much for that. However, I think I still have to resolve the underlying problem whereby my individual patches are classified as individuals in `class` as opposed to 'id'. 

For example, I am also looking to calculate ENN_mn from the patch and the output is as such: 
# A tibble: 11 x 6
   layer level class    id metric value
   <int> <chr> <int> <int> <chr>  <dbl>
 1     1 class     1    NA enn_mn  NA  
 2     1 class     2    NA enn_mn  NA  
 3     1 class     3    NA enn_mn  NA  
 4     1 class     4    NA enn_mn  NA  
 5     1 class     5    NA enn_mn  NA  
 6     1 class     6    NA enn_mn  NA  
 7     1 class     7    NA enn_mn  NA  
 8     1 class     8    NA enn_mn  NA  
 9     1 class     9    NA enn_mn  NA  
10     1 class    10    NA enn_mn  NA  
Warning messages:
1: Class 1: ENN = NA for class with only 1 patch. 
2: Class 2: ENN = NA for class with only 1 patch. 
3: Class 3: ENN = NA for class with only 1 patch. 
4: Class 4: ENN = NA for class with only 1 patch. 
5: Class 5: ENN = NA for class with only 1 patch. 
6: Class 6: ENN = NA for class with only 1 patch. 
7: Class 7: ENN = NA for class with only 1 patch. 
8: Class 8: ENN = NA for class with only 1 patch. 
9: Class 9: ENN = NA for class with only 1 patch. 
10: Class 10: ENN = NA for class with only 1 patch. 

So I wonder if there is anything I can do to change the format of the raster by classifying the polygons in the same class, but while identifying them uniquely? I think this might solve a lot of my issues and allow me to use the other functions in the package. 

Again, thanks for your help. I really appreciate your help so far :)

Cheers,

Rick

**Comment by mhesselbarth** [comment]
Got it. Simply reclassify all your patches giving them the same value. Since they all are separated by NAs, they automatically will be identified as unique patches. Of course, you could also reclassify all NAs additionally as e.g. class 99.

To check if that worked and obtain the original raster again, you could use `get_patches()` which will label and return all patches of the class (basically your original raster, will be returned as a list in which each list entry represents a class).

``` r
library(dplyr)
library(raster)
library(landscapemetrics)
library(rgdal)
library(sp)

utm_crs <- c("+proj=utm +datum=WGS84 +zone=56H +south=T +no_defs +ellps=WGS84 +towgs84=0,0,0") 
CrookhavenOysters <- readOGR("~/Desktop/CrookhavenOysters.kml")
Crookhavenreefs <- spTransform(CrookhavenOysters, utm_crs)
CR_rast <- raster(extent(Crookhavenreefs), res = 0.05, crs = utm_crs) 
Crookhaven_rast <- rasterize(Crookhavenreefs, CR_rast,update = TRUE)

check_landscape(Crookhaven_rast)
#>   layer       crs     units   class n_classes OK
#> 1     1 projected +proj=utm integer        10  ✓

Crookhaven_rast_reclass <- Crookhaven_rast
Crookhaven_rast_reclass[!is.na(Crookhaven_rast_reclass)] <- 1
# Crookhaven_rast_reclass[is.na(Crookhaven_rast_reclass)] <- 99

lsm_p_enn(Crookhaven_rast_reclass)
#> # A tibble: 10 x 6
#>    layer level class    id metric value
#>    <int> <chr> <int> <int> <chr>  <dbl>
#>  1     1 patch     1     1 enn     5.73
#>  2     1 patch     1     2 enn     5.73
#>  3     1 patch     1     3 enn    10.2 
#>  4     1 patch     1     4 enn     2.69
#>  5     1 patch     1     5 enn     6.24
#>  6     1 patch     1     6 enn     6.11
#>  7     1 patch     1     7 enn     2.69
#>  8     1 patch     1     8 enn     7.31
#>  9     1 patch     1     9 enn    22.5 
#> 10     1 patch     1    10 enn    27.6

Crookhaven_rast_original <- get_patches(Crookhaven_rast_reclass)[[1]]
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rickcleong** [comment]
Hey Max,

I think that's it the issue has been solved! Danke schon for your help! :) Keep us updated on any additional functions in the package! :)
