### ISSUE TITLE
Landscape heterogeneity index

### ISSUE THREAD

**Issue by chencaf** [r-spatialecology/landscapemetrics#180]
Hi, bro,could you add a new index(Landscape heterogeneity index)?Below are the titles and links of the literature：
A Novel Method for Measuring Landscape Heterogeneity Changes(https://www.researchgate.net/publication/269725687_A_Novel_Method_for_Measuring_Landscape_Heterogeneity_Changes?_iepl%5BgeneralViewId%5D=9IgR9aKeGo0LkExoo2ZM1zDSbSWOYxqdFEnN&_iepl%5Bcontexts%5D%5B0%5D=searchReact&_iepl%5BviewId%5D=tHTRtmiGNbDr6ig5ofqnOOswZt5T3S9Ahpz3&_iepl%5BsearchType%5D=publication&_iepl%5Bdata%5D%5BcountLessEqual20%5D=1&_iepl%5Bdata%5D%5BinteractedWithPosition1%5D=1&_iepl%5Bdata%5D%5BwithoutEnrichment%5D=1&_iepl%5Bposition%5D=1&_iepl%5BrgKey%5D=PB%3A269725687&_iepl%5BtargetEntityId%5D=PB%3A269725687&_iepl%5BinteractionType%5D=publicationTitle)

Good luck！
Cheers

**Comment by bitbacchus** [comment]
Before we invest time and effort to research if it is possible to implement, please let us know:

- what are you planning to use the index for?
- why you can't / don't want to use one of the existing indices instead?

Best,
Sebastian

**Comment by mhesselbarth** [comment]
Hey, 

I just read the paper quickly and it seems like the LHI is based on numerical (i.e. continuous) values for each cell (even though they work with a binary map of change vs. non-change). However, the `landscapemetrics` package is designed for categorical (i.e. discrete) values for each cell. 

So, at this point, the LHI is not within the scope of this package and thus won't be implemented, unfortunately, as far as I can see.
