### ISSUE TITLE
Calculate metrics per buffer: potential applications for parallel processing

### ISSUE THREAD

**Issue by frederikvand** [r-spatialecology/landscapemetrics#182]
Generally I calculate landscapemetrics for buffers in a landscape (around points with field measurements). I noticed that when I give the whole raster as input, the calculations go very slow. However, when I crop and mask each buffer in a loop the calculation goes more than 50% faster. Furthermore, this opens up possibilities for parallel calculations (with e.g. foreach), progress bars and the use of apply (also potentially in parallel). Would this be an interesting application? If I apply this on the cluster with 36 cores in parallel this would potentially mean a 99.99% time gain. 

General example with loop instead of apply:

A simple test case with 1 million raster cells and 100 points: 
square_all = sample_lsm(raster, y = centroid_small, size = 1000)

=> 828.46 seconds

  system.time({for (c in 1:nrow(centroid_small)) {
                    print(c)
                    raster_crop <- crop(raster, Buffer_1000[c,])
                    raster_crop_mask <- mask(raster_crop, Buffer_1000[c,])
                    assign(paste("raster_crop_mask", Buffer_1000$id[c], sep = '_'), raster_crop_mask)
                    progress(c, progress.bar = TRUE)
                    rm(raster_crop) # I tried to gain memory
                    rm(raster_crop_mask) # I tried to gain memory
                    gc() # idem
  }
  
  ID_mask <- paste("raster_crop_mask", Buffer_1000$id, sep = '_')
  mask_list = lapply(ID_mask, get)
  ID <- Buffer_1000$id
 
#Calculate class metrics in for loop
  for (i in seq(ID_mask)){
    lsm <- calculate_lsm(mask_list[[i]], 
                         level = c("patch",  "class"))
    lsm$ID <- ID[i]
    assign(paste("lsm_c", ID[i], sep = '_'), lsm)
    progress(i)
    gc() # idem
  }})

#Make list of raster names
lsm_c_list <-   paste("lsm_c", ID, sep = '_')

#reduce all dataframes
lsm_c_df_list = lapply(lsm_c_list, get)
lsm_c_data = Reduce(function(...) merge(..., all=T), lsm_c_df_list)

  
=> 399.31 seconds

**Comment by mhesselbarth** [comment]
Interesting that cropping and masking before makes it so much faster. That's basically the same what we do internally in the `sample_lsm()` function. Maybe we need to check why it gets that slow.

I discussed parallelisation a lot in the team but decided to not include it in the package. The reason for this is that an internal parallelisation could lead to serious issues if the users decided then to parallelise on top of that (maybe without knowing exactly what we and they are doing). So we recommend if you want to do it in parallel (and yes the sampling is a good example where it is possible) to do the parallelisation on the highest level, i.e. the user.

**Comment by frederikvand** [comment]
Thanks for the clarification! 

In the raster package it's the same issue when the beginCluster() function is used. I think the package user-friendlyness would definitely benefit from parallel processing and a simple warning to not include the parallel function when someone is already using parallel processing would be enough I think. There is a more steep learning curve to write your own parallel functions than to just write beginparallel(). Furthermore seeing the progress on slow functions is also a big improvement!
