### ISSUE TITLE
Warning loading/installing package

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#187]
Is someone else getting the following warning since a few days/weeks? 

``` r
library(landscapemetrics)
#> Warning: multiple methods tables found for 'wkt'
```

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
I am not. (Tested on two Fedora computers, one with R 3.6 and one with R 4.0)

**Comment by mhesselbarth** [comment]
I don't get the message on macOS. So seems to be specific to Windows or to my desktop computer in the office. I will try to check with `rhub`.

**Comment by mhesselbarth** [comment]
Seems to be a problem of my system

**Comment by csim063** [comment]
No issue on my Windows system
