### ISSUE TITLE
Issue with sample_lsm, no output, never-ending run

### ISSUE THREAD

**Issue by Morganelegoff** [r-spatialecology/landscapemetrics#191]
Hello, 

For a project, I need to compute an edge density in a 100 meters buffer around specific points.
I used 'sample_lsm' which seems to be a perfect match with what I wanted to do, as follow:
`sample_lsm(landcover, y=sample_points, shape='circle', size=100,what='lsm_c_ed')`

With:
'landcover'=raster
'sample_points' = matrix of the points, 2 columns

R runs the function but it never ends, no error message, just no output, even after hours.

Can you help me with that issue?
Thank you, 

Morgane

**Comment by mhesselbarth** [comment]
Hey, 

Is there a way you could share your data with us? It sounds a bit like your landscape or your number of sample points might be just too big, but it's hard to debug/help without the data.

**Comment by Morganelegoff** [comment]
Hey,

Unfortunately, I can't share the data.
That is my guess too, too big, but is there any alternative way to do what I want?

I have 35 510 data points, I could subset my data in chunks of 9659, 14222 and 11629 data points but I don't know what is considered 'too much' data points.

The dimensions of my raster are :
 835 804   1


Hope this helps.
`

**Comment by bitbacchus** [comment]
Hm, maybe you could provide some fake data that reproduces the issue? This doesn't seem too big (at least for my gut feeling)...

**Comment by mhesselbarth** [comment]
It's hard to help without any reproducible example. One suggestion would be to set `progress = TRUE`. This could give some insights maybe.

**Comment by Morganelegoff** [comment]
So the `progress=TRUE` was actually helpful, 1 plot/sec with 35 510 plot to compute, it will take ~10 hours. 
So I will try with another computer as soon as I get a chance, hopefully faster.

**Comment by mhesselbarth** [comment]
Another idea would be to use parallel computing with e.g. the help of the `furrr` package: 

``` r
library(landscapemetrics)
library(future)
library(furrr)

future::plan(multiprocess)
#> Warning: [ONE-TIME WARNING] Forked processing ('multicore') is disabled
#> in future (>= 1.13.0) when running R from RStudio, because it is
#> considered unstable. Because of this, plan("multicore") will fall
#> back to plan("sequential"), and plan("multiprocess") will fall back to
#> plan("multisession") - not plan("multicore") as in the past. For more details,
#> how to control forked processing or not, and how to silence this warning in
#> future R sessions, see ?future::supportsMulticore

# use a matrix
sample_points <- matrix(c(10, 5, 25, 15, 5, 25), ncol = 2, byrow = TRUE)

result <- furrr::future_map(1:nrow(sample_points), function(i) {
  sample_lsm(landscape, y = matrix(sample_points[i, ], ncol = 2), 
             size = 15, what = "lsm_c_ed")
})
#> Warning: The 'perecentage_inside' is below 90% for at least one buffer.
#> Warning: Please use 'check_landscape()' to ensure the input data is valid.
#> Warning: The 'perecentage_inside' is below 90% for at least one buffer.
#> Warning: Please use 'check_landscape()' to ensure the input data is valid.
#> Warning: The 'perecentage_inside' is below 90% for at least one buffer.
#> Warning: Please use 'check_landscape()' to ensure the input data is valid.

result <- dplyr::bind_rows(result, .id = "plot_id_rbind")
result
#> # A tibble: 9 x 9
#>   plot_id_rbind layer level class    id metric value plot_id percentage_inside
#>   <chr>         <int> <chr> <int> <int> <chr>  <dbl>   <int>             <dbl>
#> 1 1                 1 class     1    NA ed     2220        1              55.6
#> 2 1                 1 class     2    NA ed     2600        1              55.6
#> 3 1                 1 class     3    NA ed     3980        1              55.6
#> 4 2                 1 class     1    NA ed     2117.       1              66.7
#> 5 2                 1 class     2    NA ed     2467.       1              66.7
#> 6 2                 1 class     3    NA ed     3517.       1              66.7
#> 7 3                 1 class     1    NA ed     2225        1              44.4
#> 8 3                 1 class     2    NA ed     2000        1              44.4
#> 9 3                 1 class     3    NA ed     3425        1              44.4
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mhesselbarth** [comment]
Seems to be solved. Please re-open if you have further questions.
