### ISSUE TITLE
Reinventing input preprocessing

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#204]
Currently, we have a lot of repeated code in most of our functions. For example, https://github.com/r-spatialecology/landscapemetrics/blob/master/R/lsm_l_shdi.R - we are doing almost the same (but for different input classes) five times between line 46 and 120. This makes adding a new input class quite tedious - we need to add (and later maintain) another several lines of code in a few dozen files. 

I thought about this problem for some time, and my proposed solution is to create a new function (`prepare_input()`) that understands different classes and returns a proper data structure. Next, this function can be used in most of the other functions.
I prepared a pull request with this idea. Just look at two files - `R/prepare_input.R` and `R/lsm_l_shdi.R` at https://github.com/r-spatialecology/landscapemetrics/pull/203.

What do you think about that?

Related: https://github.com/r-spatialecology/landscapemetrics/issues/202

**Comment by mhesselbarth** [comment]
I think this might be a good idea!

**Comment by Nowosad** [comment]
Great. I will wait for @bitbacchus opinion before making any changes.

**Comment by bitbacchus** [comment]
Brilliant idea, this totally makes sense! I'd suggest a better name, however. What the function does in essence, is convert anything to a list that the `lsm` functions can handle, right? How about `landscapemetrics:::as.list()` or `lsm_as_list()` ?

**Comment by Nowosad** [comment]
Awesome. I am fine with `lsm_as_list()`. I plan to implement these changes soon.

**Comment by mhesselbarth** [comment]
I would argue against `lsm_as_list()` because the `lsm_` prefix is reserved for functions that return a metric. Don't have a better idea at the moment though. But since the function will only be internal, we don't really need a catchy name anyways, right?

**Comment by bitbacchus** [comment]
Yes, it's internally, but a good name is always desirable, IMHO.

as_list
as.list
ls_as_list
landscape_as_list

?

**Comment by mhesselbarth** [comment]
I don't mind longer names, especially thanks to the auto-complete of RStudio. So I like `landscape_as_list()`, or if that's too long `ls_as_list()` is also good *imho*

**Comment by Nowosad** [comment]
Great discussion. I ended up with using `landscape_as_list()`. You can find all of the changes at https://github.com/r-spatialecology/landscapemetrics/pull/203. 

Please merge the PR if you are happy with it or let me know what else should be done.

When this PR is accepted, then I plan to work on adding Terra support.

**Comment by mhesselbarth** [comment]
Merged 🎉
