### ISSUE TITLE
‘raster’ for: ‘wkt’

### ISSUE THREAD

**Issue by jesseseeem** [r-spatialecology/landscapemetrics#207]
Hi, I just ran "install.packages("landscapemetrics", dependencies = TRUE) on R 4.02 (on macOS Catalina 10.15.6)
when I tried to load the library, I got the following warning message: 
 
Warning message:
no function found corresponding to methods exports from ‘raster’ for: ‘wkt’ 

Unclear if this has any real downstream consequences, but I just wanted to let you know. 
Thanks for all your hard work on this project!

**Comment by mhesselbarth** [comment]
This seemed to be an issue of `raster` but seems to be fixed. Will close this for now, please re-open if necessary
