### ISSUE TITLE
Trouble with the lsm_c_cpland function

### ISSUE THREAD

**Issue by fabiolexcastro** [r-spatialecology/landscapemetrics#209]
Hi, 

We are using your landscape metrics library in a project for Casanare - Colombia. 

We realized that the final result is not equal to 100 for all the classes values. The total sum for all classes is 52%, furthemore we computed the NAs from the total raster and the results is 92%, so there isn't a match between them. For the moment we created our own function, something like this:

rsl <- rst %>% 
    rasterToPoints %>% 
    as_tibble() %>% 
    setNames(c('x', 'y', 'cov')) %>% 
    group_by(cov) %>% 
    dplyr::summarise(count = n()) %>% 
    ungroup() %>% 
    mutate(porc = count / sum(count) * 100) 

Thanks and we are looking for any advise. 

Best regards, 
Fabio Castro

**Comment by mhesselbarth** [comment]
`lsm_c_cpland()` is the core area percentage of a landscape. Thus, it cannot be 100 % by definition because there always has to be an edge so that there can be a core area. 

If you want to get the relative class area (which should add up tp 100%) you need to use `lsm_c_pland()`.

Cheers,
Max

**Comment by mhesselbarth** [comment]
Will close for now. Please re-open if necessary
