### ISSUE TITLE
sample_lsm recognize different length of y 

### ISSUE THREAD

**Issue by hugocmcosta** [r-spatialecology/landscapemetrics#210]
Hi, I am using sample_lsm to extract landcover metrics using an sf multipolygon object as y which possesses 81 observations, however, when running sample_lsm (progress = TRUE) it recognizes 82 observations and uses 1...n as plot_id. I have tried with the same vector layer with RGDAL and this warning persists. 
Thank you!

**Comment by mhesselbarth** [comment]
Can you provide a reproducible code example with the data you are using?

**Comment by hugocmcosta** [comment]
Unfortunately, I am not able to do so. Do you mind if I send you the data?

**Comment by mhesselbarth** [comment]
Not at all. Just drop me an [email](mailto:mhk.hesselbarth@gmail.com) and I can have a look at it

**Comment by mhesselbarth** [comment]
The issue is that one of your `MULTIPOLYGON`s actually contains two `POLYGON`s and `sample_lsm()` samples the metrics for each of them.

``` r
library(sf)
library(raster)
library(landscapemetrics)

# load shape file
shp <- sf::st_read("~/Desktop/lsm/poligonos_imoveis_rurais_entrevistados_albers.shp")
#> Reading layer `poligonos_imoveis_rurais_entrevistados_albers' from data source `/Users/mhesselbarth/Desktop/lsm/poligonos_imoveis_rurais_entrevistados_albers.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 81 features and 60 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -60.30612 ymin: -15.21209 xmax: -50.34857 ymax: -8.708642
#> projected CRS:  South_America_Albers_Equal_Area_Conic

# check the number of polys for each multiply
n_poly <- purrr::map_int(shp$geometry, length)

# row 60 has more than one poly
which(n_poly > 1)
#> [1] 60

# plot row 60
plot(shp$geometry[60])
```

![](https://i.imgur.com/9abQ7tg.png)

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Cheers,
Max

**Comment by hugocmcosta** [comment]
Thank you, Max! I will correct it and try again.

Cheers, 
Hugo

**Comment by mhesselbarth** [comment]
Will close for now. Please reopen if needed.

**Comment by hugocmcosta** [comment]
Dear max, I am heaving the same issue. I checked if there is more than one poly as you did previously. 
Here is a reproducible code example with the data: 

r<- raster(ncol = 100, nrow = 100, 
           xmn= -9415.64, xmx = 1244535, 
           ymn = -1998974, ymx = -812493.4,
           crs = "+proj=utm +zone=21 +units =m +datum=WGS84")

values(r) <- sample(x = c(1:8),
                    size = ncell(r), 
                    replace = TRUE,
                    prob = c(0.1, .25, .40,.07, .15,.01,.2,.6))

install.packages("geobr")
library(geobr)

shp <-  read_municipality(code_muni= "MT", year = 2017)
shp <- sf::st_transform(municipios,crs(r))

# check the number of polys for each multiply
n_poly <- purrr::map_int(shp$geometry, length)
which(n_poly > 1)

check_landscape(r)

class.area <- sample_lsm(r , shp,
           plot_id = "name_muni",
           what = "lsm_c_ca", 
           return_raster = FALSE)

**Comment by mhesselbarth** [comment]
I think something in how you check the number of polygons is not correct because there `MULTIPOLYGONS` contain more than one `POLYGON` again. 

``` r
library(raster)
library(geobr)
library(sf)

r <- raster(ncol = 100, nrow = 100,
            xmn= -9415.64, xmx = 1244535,
            ymn = -1998974, ymx = -812493.4,
            crs = "+proj=utm +zone=21 +units =m +datum=WGS84")

values(r) <- sample(x = c(1:8),
                    size = ncell(r),
                    replace = TRUE,
                    prob = c(0.1, .25, .40,.07, .15,.01,.2,.6))

shp <- read_municipality(code_muni = "MT", year = 2017)

shp <- sf::st_transform(shp, crs(r))

n_poly <- purrr::map_int(shp$geom, length)

(id <- which(n_poly > 1))
#> [1]  16  94 103

plot(shp$geom[16])
```

![](https://i.imgur.com/3Rq3bvu.png)

``` r

(multi_split <- sf::st_cast(shp$geom[94], to = "POLYGON"))
#> Geometry set for 3 features 
#> geometry type:  POLYGON
#> dimension:      XY
#> bbox:           xmin: 173208.5 ymin: -1792710 xmax: 289057.4 ymax: -1621953
#> CRS:            +proj=utm +zone=21 +units =m +datum=WGS84
#> POLYGON ((248618.3 -1646083, 248618 -1646083, 2...
#> POLYGON ((267471.9 -1632178, 267472.4 -1632180,...
#> POLYGON ((248618.3 -1646083, 248784.3 -1646116,...

plot(multi_split[1])
```

![](https://i.imgur.com/6jZ04PW.png)

``` r
plot(multi_split[2])
```

![](https://i.imgur.com/HiMyfF7.png)

``` r
plot(multi_split[3])
```

![](https://i.imgur.com/NNu75pr.png)

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hugocmcosta** [comment]
Yes! I was using purrr::map_int(shp$geometry, length) instead of shp$geom

Thank you again!

**Comment by hugocmcosta** [comment]
Dear Max,
 I am working with a huge dataset with 124k polygons which 45k have more than one polygon. 
Do you have any clue on how can I deal with this issue? You can use the data on your previous comment if you wish.
Thank you!

**Comment by mhesselbarth** [comment]
That's is a question rather related to `sf` than `landscapemetrics` so maabe rather ask [here](https://github.com/r-spatial/sf/issues) I would suggest.

But I would probably just try to write a loop/`map` and cast them all to single polygons if that's reasonable on a local machine.

**Comment by Nowosad** [comment]
FYI: you can cast MULTIPOLYGONs into POLYGONs with `st_cast()`:

```r
sp = st_cast(mp, "POLYGON")
```

**Comment by hugocmcosta** [comment]
Thank you, Max and Nowsad. I will follow your suggestions
