### ISSUE TITLE
Visualizing edge

### ISSUE THREAD

**Issue by fabiolexcastro** [r-spatialecology/landscapemetrics#212]
Dear Maximillian, 

Could you provide me an advice to visualize the patch edge  as a raster file to compare with the patch area. We are looking at the library functions and we haven't found it. Thanks a lot.

Good times, 
Fabio Castro / Erika Arias

**Comment by mhesselbarth** [comment]
Does this answer your question? 

``` r
library(landscapemetrics)
library(raster)

show_cores(landscape, class = 1)
```

![](https://i.imgur.com/7QtJf6V.png)

``` r


class_1 <- get_patches(landscape, class = 1)[[1]]
get_boundaries(class_1)
#> [[1]]
#> class      : RasterLayer 
#> dimensions : 30, 30, 900  (nrow, ncol, ncell)
#> resolution : 1, 1  (x, y)
#> extent     : 0, 30, 0, 30  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : memory
#> names      : layer 
#> values     : 0, 1  (min, max)
```

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fabiolexcastro** [comment]
Thanks a lot, it works
