### ISSUE TITLE
ENN

### ISSUE THREAD

**Issue by fabiolexcastro** [r-spatialecology/landscapemetrics#213]
Hello!

We are using the euclidean neighboord distance and we already obtained the data table. We are looking forward to visualize them geographically. The main point is that within the data table we can't find geographically coordinates for the patch id, we highly appreciate any advance with this issue. 

Best regards from Cali / Colombia
Fabio Castro

**Comment by bitbacchus** [comment]
Hi Fabio,

is this helpful, already?

`landscapemetrics::show_patches(landscape = landscape, class = 1, labels = TRUE)`

**Comment by mhesselbarth** [comment]
You can also have a look at `spatialize_lsm()`

**Comment by fabiolexcastro** [comment]
Dear bitbacchus and mshesselbarth

Thanks a lot for your quick reply. 

After having used this function: 

`tst <- spatialize_lsm(stk, metric = 'enn', level = 'patch')`

We obtained three raster as an output, but we don't have an idea of making and interpretation of them. We have seven classes and we thought to obtain seven raster as an output.

We appreciate any advance!

Best regards, 
Fabio Castro / Erika Arias

**Comment by mhesselbarth** [comment]
It's really hard to help without any reproducible code snippets. One possibility I could think of why you get three rasters is that `stk` is a `RasterStack` or `RasterBrick`

``` r
library(landscapemetrics)
library(raster)

# RasterLayer returns one RasterLayer
spatialize_lsm(landscape, metric = 'enn', level = 'patch')
#> Warning: Please use 'check_landscape()' to ensure the input data is valid.
#> [[1]]
#> [[1]]$lsm_p_enn
#> class      : RasterLayer 
#> dimensions : 30, 30, 900  (nrow, ncol, ncell)
#> resolution : 1, 1  (x, y)
#> extent     : 0, 30, 0, 30  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : memory
#> names      : value 
#> values     : 2, 7  (min, max)

# stack raster
lsm_stack <- raster::stack(landscape, landscape)

# RasterStack returns one RasterLayer for each layer of the original stack
spatialize_lsm(lsm_stack, metric = 'enn', level = 'patch')
#> Warning: Please use 'check_landscape()' to ensure the input data is valid.

#> Warning: Please use 'check_landscape()' to ensure the input data is valid.
#> [[1]]
#> [[1]]$lsm_p_enn
#> class      : RasterLayer 
#> dimensions : 30, 30, 900  (nrow, ncol, ncell)
#> resolution : 1, 1  (x, y)
#> extent     : 0, 30, 0, 30  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : memory
#> names      : value 
#> values     : 2, 7  (min, max)
#> 
#> 
#> 
#> [[2]]
#> [[2]]$lsm_p_enn
#> class      : RasterLayer 
#> dimensions : 30, 30, 900  (nrow, ncol, ncell)
#> resolution : 1, 1  (x, y)
#> extent     : 0, 30, 0, 30  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : memory
#> names      : value 
#> values     : 2, 7  (min, max)
```

<sup>Created on 2020-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mhesselbarth** [comment]
Will close for now. Please re-open if necessary.
