### ISSUE TITLE
Segfault in lsm_c_ai

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#220]
I get the following error when running the test for `lsm_c_ai` recently. Also `lsm_c_ai` crashes my R Session completely. Is somebody else having issues? Strangely the GitHub action seemed not to fail on the last push, so probably a local problem on my machine? Seems to be related to `rcpp_get_coocurrence_matrix_diag`

```
*** caught segfault ***
address 0x7ffe00000000, cause 'memory not mapped'
```

**Comment by Nowosad** [comment]
Never happened to me. Do you have any reprex?

**Comment by mhesselbarth** [comment]
I had to delete the Rcpp export, re-compile and clean and rebuild everything. Now it's working again...No idea what the heck that was.
