### ISSUE TITLE
SpatRaster compatibility?

### ISSUE THREAD

**Issue by FrancoiseCardou** [r-spatialecology/landscapemetrics#225]
Hello all - 

I've been runing into issues sampling a large raster landscape using the sample_lsm function (landscapemetrics v1.5.2). The documentation states that it should be compatible with class SpatRaster, but when I run the function, I get "no method for 'sample_lsm' available for object of class SpatRaster" (translating losely from my french-speaking console).

Is landscapemetrics compatible with terra or am I missing something obvious?

Any help would be appreciated, 

Françoise

SpatRaster properties:

class       : SpatRaster 
dimensions  : 84886, 116516, 1  (nrow, ncol, nlyr)
resolution  : 0.5, 0.5  (x, y)
extent      : -8865430, -8807172, 5400731, 5443174  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs 
source      : perm_wgs84.tif 
name        : perm_wgs84 
min value   :                  0 
max value   :                  1

**Comment by mhesselbarth** [comment]
I know that @Nowosad implemented `terra` support at one point. But it seems like only for all core metrics and not for any of the "wrapper" functions (e.g., `sample_lsm`, `window_lsm`, etc.). I am not sure why? Probably we just forgot this I would assume.

Saying this, internally `SpatRaster`objects are converted to `raster` objects first and then to `matrix` anyways. So a quick fix for you would be to convert the `terra` object to a `raster` "manually" before passing it to `sample_lsm`.

**Comment by Nowosad** [comment]
Yes, "wrapper" functions still need some work to accept terra objects. I will implement that in the coming days.

**Comment by mhesselbarth** [comment]
I just had a quick look at the code. The same/similar structure as for the core metrics should work though, right?

**Comment by Nowosad** [comment]
Yes, I would assume so.

**Comment by FrancoiseCardou** [comment]
Thanks guys, 

I was hoping to use SpatRaster because they require less memory, however, if the function simply converts them back into raster,  internally, I now realize that would have probably not helped. Doing the same operation with the RasterLayer (properties below) prompts an error "cannot allocate vector of size 30Go", even when sampling for just 1 metric (lsm_c_pland) at a handful of plots.  I saw there had previously been an issue raised here about this a few months ago, but the o.p. didn't seem to come up with a solution.

Either way, thanks for following up!

Françoise

class      : RasterLayer 
dimensions : 84886, 116516, 9890577176  (nrow, ncol, ncell)
resolution : 0.5, 0.5  (x, y)
extent     : -8865430, -8807172, 5400731, 5443174  (xmin, xmax, ymin, ymax)
crs        : +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs 
source     : ./data/permeability/perm_wgs84.tif 
names      : perm_wgs84 
values     : 0, 1  (min, max)

**Comment by mhesselbarth** [comment]
Will close for now since now all functions should support terra (see #226). However, since all objects or converted into a matrix internally, now speed improvements are expected!
