### ISSUE TITLE
Expand of the terra support

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#226]
I started working on a new branch - `terra3` - https://github.com/r-spatialecology/landscapemetrics/tree/terra3.

It adds terra objects (SpatRaster) support for `calculate_lsm()`, `check_landscape()`, `extract_lsm()`, `sample_lsm()`, `scale_sample()`, `scale_window()`, `spatialize_lsm()`, `window_lsm()`.

If you look at NAMESPACE, it could also be possible to add this support to some other functions, such as:

- `get_adjacencies()` - however, this function supports `matrix` objects as well
- `get_boundaries()`
- `get_centroids()`
- `get_circumscribingcircle()`
- `get_nearestneighbour()`
- `get_patches() - however, this function supports `matrix` objects as well
- `get_unique_values()` - however, this function supports `matrix` and `numeric` objects as well
- `pad_raster()` - however, this function supports `matrix` objects as well
- `raster_to_points()`
- `unpad_raster()` - however, this function supports `matrix` objects as well
- `show_cores()` - however, then its tests are failing (I would assume it could also happen to the following two functions)
- `show_lsm()`
- `show_patches()`

However, there are some possible problems:
1. Some functions support additional classes - what should we do here?
2. Some functions (e.g. `show_cores()`) fails tests after modifications are done.
3. Some functions are interrelated and fail strangely (we could work on that as the last step)

@mhesselbarth could you help me untangle these issues one by one? For example, could you try to modify the `show_cores()` in the same fashion as I have done for `calculate_lsm()` and see why it renders an error?

Also - do we need/want all of them to support terra classes?

Related: #225

**Comment by mhesselbarth** [comment]
Sure, I will look into this probably next week!

**Comment by mhesselbarth** [comment]
Just a quick question...what is `terra2`?

**Comment by Nowosad** [comment]
Garbage. Feel free to remove it.

**Comment by mhesselbarth** [comment]
Progress: 

- [ ] get_adjacencies()
- [ ] get_boundaries()
- [ ] get_centroids()
- [ ] get_circumscribingcircle()
- [ ] get_nearestneighbour()
- [ ] get_patches()
- [ ] get_unique_values()
- [ ] pad_raster()
- [ ] raster_to_points()
- [ ] unpad_raster()
- [ ] show_cores() 
- [ ] show_lsm()
- [ ] show_patches()

**Comment by mhesselbarth** [comment]
1a831e7

I added terra support for most functions with three exceptions. For the remaining three functions the structural changes might be a bit more complicated (but not impossible) I think

**Comment by Nowosad** [comment]
Great work @mhesselbarth. The question is - are those three functions useful for our users, or should they be an internal function only?

**Comment by mhesselbarth** [comment]
I feel like `get_unique_values` might be, the padding stuff probably not.

**Comment by mhesselbarth** [comment]
#229

Okay, `get_unique_values` is also done. Pull request should be good to merge.

**Comment by Nowosad** [comment]
Neat. @mhesselbarth have you considered unexporting these padding functions?

**Comment by mhesselbarth** [comment]
I decided to add terra support for padding too. I don't think anyone will ever use this, but basically the same code structure as `get_unique_values`.
