### ISSUE TITLE
question

### ISSUE THREAD

**Issue by JASSI24** [r-spatialecology/landscapemetrics#236]
how can i visualize class level metrics like  for lsm _c _pland?

**Comment by mhesselbarth** [comment]
Hey, 

On patch-level `landscapmetrics` has build-in functions for either getting a raster in which all patches have the value of the corresponding patch metric (`spatialize_lsm` or using the build-in plotting functions directly (`show_lsm`). 

On class-level, `landscapmetrics` has no build-in function for this yet, however, it's quite easy to program that yourself (see code example)

``` r
library(raster)
library(landscapemetrics)
library(tidyverse)

# get spatial result of patch area
result_ras <- spatialize_lsm(landscape = augusta_nlcd, what = "lsm_p_area")

# plot raster layer
plot(result_ras$layer_1$lsm_p_area)
```

![](https://i.imgur.com/JdmZyuR.png)

``` r
# use build in plotting function
landscapemetrics::show_lsm(landscape = augusta_nlcd, what = "lsm_p_area")
#> $layer_1
```

![](https://i.imgur.com/0AgVm1f.png)

``` r
# calculate metric on class level
pland <- lsm_c_pland(landscape = augusta_nlcd)

# create data.frame with xy coordinate and class value
# left join result of class metric by class
# only select needed cols
# create raster with same spatial characteristics
pland_spatial <- cbind(raster::coordinates(augusta_nlcd), 
                       class = raster::values(augusta_nlcd)) %>% 
  tibble::as_tibble() %>% 
  dplyr::left_join(pland, by = "class") %>% 
  dplyr::select(x, y, value) %>% 
  raster::rasterFromXYZ(res = raster::res(augusta_nlcd), crs = raster::crs(augusta_nlcd))

plot(pland_spatial)
```

![](https://i.imgur.com/bKRa0a0.png)

<sup>Created on 2021-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Standard output and standard error
</summary>

``` sh
x Install the styler package in order to use `style = TRUE`.
```

</details>

**Comment by JASSI24** [comment]
Hello, 
When i am using this code for my raster data it shows me error. Please tell how to correct this.
code.......# plot raster layer
plot(result_ras$layer_1$lsm_p_area)
error.....Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf

**Comment by JASSI24** [comment]
hello
Also if i want to do landscape level metrices can i use the same codes for that also? Like if i want to use largest patch index for only one class like for built-up.

**Comment by mhesselbarth** [comment]
First, on landscape-level it doesn't make sense to plot any metric values, because the value would be identical for each cell in the landscape. 

Second, can you maybe share your raster? It's impossible to debug your issue with being able to reproduce it.

**Comment by JASSI24** [comment]
Hi @mhesselbarth, 
i am unable to share tiff files in here. So i have share it on your mail id . Please check.

**Comment by mhesselbarth** [comment]
I checked but didnt receive an email, sorry. You can also drag&drop files into the text box here though

**Comment by mhesselbarth** [comment]
Please reopen if needed but solved in email correspondence imo
