### ISSUE TITLE
Inquiry about i,j,n meaning

### ISSUE THREAD

**Issue by YaquanChang** [r-spatialecology/landscapemetrics#237]
Hi,

I was trying to understand how the lsm_c_cohesion function works by reading the equation. But it is not clear the meaning of i,j,n in the equation. can we tell me what do they mean? Thanks in advance!

best,
Yaquan

**Comment by mhesselbarth** [comment]
Hey Yaquan, 

The _i_ and _j_ stand for the class and patch id, while _n_ describes the sum over all present patches.

Maybe the more comprehensive documentation of FRAGSTATS is also helpful to you ([Link](https://www.umass.edu/landeco/research/fragstats/documents/fragstats.help.4.2.pdf)).
