### ISSUE TITLE
Question about Background Values

### ISSUE THREAD

**Issue by alyshav** [r-spatialecology/landscapemetrics#244]
Hello,

I have two questions regarding background values: 
1) In FragStats, there is a parameter called "background value" that can be set when adding data layers. Is there a way to specify this background value in landscapemetrics? Or do I need to set my background values manually to -999 or something similar?
2) I am wondering if background values are taken into account in the landscape-level computations?

Thanks so much for your help in advance!

**Comment by mhesselbarth** [comment]
Hey, 

Thanks for your interest in the `landscapemetrics` package. 

For most functions, all cells that are `NA` are handled as background value and are not used for the calculation of the metrics. However, for some metrics (mostly edge related), there is an argument `consider_boundary` which also includes edges to background cells.

**Comment by alyshav** [comment]
Thank you so much, this is super helpful!
