### ISSUE TITLE
CWED contrast weighted edge density

### ISSUE THREAD

**Issue by bonushenricus** [r-spatialecology/landscapemetrics#249]
Greetings
excellent landscapemetrics.
It would be interesting to add the calculation of the "contrast weighted edge density" (CWED) metric, present in both FRAGSTAT and GRASS.
Do you think it is difficult?
The difficulty is that it weighs the classes differently, and it depends on how they are attributed in a raster in R, I think.
Thank you

**Comment by mhesselbarth** [comment]
Hey, 

I just quickly looked at the CWED metric, so my idea could be completely wrong, but couldn't you just calculate the "regular" edge density first and then multiply it with the weights afterward?

**Comment by bonushenricus** [comment]
Thanks for your answer.
Wishes for a happy 2022.
Yes, I could actually do what you suggest, but the problem is that I have to do it with a moving-window, and in landscapemetrics with the moving-window function I can only calculate landscape metrics, but I need the values per class for to be able to give it some weights.

**Comment by bitbacchus** [comment]
We are working on a class-level moving window implementation (#211). When we have that, it should be trivial, right?

**Comment by mhesselbarth** [comment]
How is that related to a moving window? CWED is just another metric as far as my understanding goes...

**Comment by bitbacchus** [comment]
> How is that related to a moving window? CWED is just another metric as far as my understanding goes...

**Comment by mhesselbarth** [comment]
My bad, sorry. Didn't read that... 🙈🤷‍♂️

**Comment by mhesselbarth** [comment]
I don't think we will make any progress on this in the nearer future, sorry.
