### ISSUE TITLE
Set class as matrix

### ISSUE THREAD

**Issue by CRyan21** [r-spatialecology/landscapemetrics#250]
Hi, I'm relatively new to this field, so apologies if this is a silly question. Is it possible in the landscapemetrics tool to set one of the classes in my raster to be the 'matrix'? If so, how? Thanks

**Comment by mhesselbarth** [comment]
What do you mean by "matrix"? So basically a background class? If yes, just convert the class in the `RasterLayer` as NA.

**Comment by CRyan21** [comment]
Yes, kind of a background class, although I do need to know the
characteristics of the matrix too. I think I will instead use a mixture of
class level and landscape level metrics, excluding the matrix class at the
landscape level (using NA in my rasters). Thanks!
