### ISSUE TITLE
preserving class names after using lsm_p_area()

### ISSUE THREAD

**Issue by vjjan91** [r-spatialecology/landscapemetrics#255]
Trying to use landscapemetrics::lsm_p_area() on a particular SpatRaster, but I end up losing the associated class names from the raster after running this function. Any way to preserve it?

**Comment by Nowosad** [comment]
Hi @vjjan91 -- can you provide us with a reprex? It will greatly help to find a source of the issue and hopefully fix it.

**Comment by Nowosad** [comment]
@vjjan91 let us know if the problem still occurs.
