### ISSUE TITLE
Save output in raster format 

### ISSUE THREAD

**Issue by FVFaleiro** [r-spatialecology/landscapemetrics#258]
How can I save some outputs in raster format? Some metrics calculated by patch is interesting to show in the map instead only by the statistics. Some information like core cells, identification of patch numbers can be generated with show_cores() and show_patches(), but is limited to default settings and don't works with big rasters. 
For example, If we can identify in the raster the id for each patch, we could join the values from the output based on the patch id. Other option is generate the output in a rasterStack with the outputs and each layer is a metric for the patch (cai, ca, enn, etc) or cell (localization of the cores).

Example with the patches and cores
```
library(raster)
library(landscapemetrics)
r <- raster(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), 
                    size = ncell(r),
                    replace = T)
```
How can I get the labels (id of the patches) from this image?
`show_patches(r, labels = T)`
How can I get cell id with the cores from this image?
`show_cores(r)`

**Comment by bitbacchus** [comment]
Do you mean something like this?

```R
r_patches <- landscapemetrics::get_patches(r)
raster::values(r_patches[[1]]$class_1)

r_cores <- lsm_p_core(r)
```

**Comment by FVFaleiro** [comment]
Thanks, @bitbacchus.
How can I generalize it to associate the patch metrics (r_p_metrics object below) to each patch (r_patch object below)?

```
set.seed(1)
library(raster)
library(landscapemetrics)
r <- raster(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), 
                    size = ncell(r),
                    replace = T)
r_p_metrics <- calculate_lsm(r,  level = "patch",  directions = 8,  edge_depth = 1, neighbourhood = 8)
r_patches <- get_patches(r)
```

**Comment by bitbacchus** [comment]
I'm not sure what you mean... 
```R
> head(r_p_metrics)
# A tibble: 6 × 6
  layer level class    id metric value
  <int> <chr> <int> <int> <chr>  <dbl>
1     1 patch     1     1 area    0.02
2     1 patch     1     2 area    0.09
3     1 patch     1     3 area    0.01
4     1 patch     1     4 area    0.02
5     1 patch     1     5 area    0.01
6     1 patch     1     6 area    0.02
```
The column id is the patch id, so patch 1 (patch in the top-left corner of the patches plot ) has an area of 0.02. You can just filter the tibble for each patch:

```R
> r_p_metrics |> dplyr::filter(id == 1) 
# A tibble: 6 × 6
  layer level class    id metric  value
  <int> <chr> <int> <int> <chr>   <dbl>
1     1 patch     1     1 area    0.02 
2     1 patch     1     1 cai     0    
3     1 patch     1     1 circle  0.491
4     1 patch     1     1 contig  0.167
5     1 patch     1     1 core    0    
6     1 patch     1     1 enn    20    
...
```

**Comment by FVFaleiro** [comment]
I would like to fill the patches in the raster with the values of the metrics generated by the calculate_lsm(). However, I think the right workflow is with the function spatialize_lsm(), that I didn't know when I start this issue. If I am right, I need calculate the metrics using the first function to summarize the statistics and the second to show in the maps (code below to generate the rasters). However this approach need more computational  processing and hard drive. 
Is there another option to avoid it?

```
dev.new()
show_patches(landscape, "all")
dev.new()
par(mfrow = c(1, 2))
r_sp_area <- spatialize_lsm(r, what = "lsm_p_area")
plot(r_sp_area$layer_1[[1]], main = "area")
r_sp_enn <- spatialize_lsm(r, what = "lsm_p_enn")
plot(r_sp_enn$layer_1[[1]], main = "enn")
```

**Comment by bitbacchus** [comment]
> However this approach need more computational processing and hard drive.
> Is there another option to avoid it?

Yes, you can do something like

```R
set.seed(1)
library(raster)
library(landscapemetrics)
r <- raster(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), 
                    size = ncell(r),
                    replace = T)
r_p_metrics <- calculate_lsm(r,  level = "patch",  directions = 8,  edge_depth = 1, neighbourhood = 8)

patch_ids <- r_p_metrics |> dplyr::pull(id) |> get_unique_values() |> unlist()
r_patches <- landscapemetrics::get_patches(r, class = "global")
patches_c1 <- r_patches$layer_1$class_1

for (p_id in patch_ids) {
  value <- r_p_metrics |> 
    dplyr::filter(metric == "area") |> 
    dplyr::filter(id == p_id) |> 
    dplyr::pull(value)
  patches_c1 <- raster::reclassify(patches_c1, cbind(p_id, value))
}

landscapetools::show_landscape(patches_c1)
```

**Comment by bitbacchus** [comment]
Then I guess we can close this? Feel free to re-open if you want to discuss more on this topic.

**Comment by mhesselbarth** [comment]
I feel like this is exactly what `spatialize_lsm()` does?

**Comment by FVFaleiro** [comment]
You are right @mhesselbarth. I didn't know the function when I have started the issue. However, could be a easy function to convert the result of calculate_lsm() to raster.

**Comment by mhesselbarth** [comment]
Well...we decided to have separate function for this since `calculate_lsm` already has so many arguments and options...Glad we could help.
