### ISSUE TITLE
Calculating a single metric across multiple polygons

### ISSUE THREAD

**Issue by MikeDTaylor** [r-spatialecology/landscapemetrics#260]
I am looking to calculate landscape metrics for animals' home ranges. To do this I am using sample_lsm within a loop, with each iteration of the loop accounting for a single animals range. However, if my home range contains >1 core areas (i.e. multiple polygons) the metrics are separated based on the polygon and returned as plot_id 1 -> n, as the function is meant to do. 

In my case, I am looking to calculate the metrics across the multiple polygons and return a single output for each class across the multiple polygons. I have made a quick and dirty way to do this via multiplying each metric by the proportion of the overall area of each polygon that makes up the animal's home range and then calculating the mean. _But I was wondering if there is an inbuilt way to do this within LandscapeMetrics? Especially as this might not work for some of the more complicated metrics, and where there are zeros/NAs I think this may disproportionately skew the data._

The example below illustrates how I have done this. It is not quite perfect as the SpatVector I am using only has a single geometry, despite the two individual polygons, but I think it will suffice.

I also cannot get sample_lsm() to run using a terra SpatVector and have had to convert to SF. When using a SpatVector I get the error (_argument "size" is missing, with no default_), and following #123 I tried including size = 0, but this returns the error (_Please provide only one value as size argument (size > 0)_). I have replicated this error below, but it may be that this is not implemented currently as `help(sample_lsm)` appears to suggest that you can use a SpatRaster in the landscape input, but does not list SpatVector as ann input for y.

If there are any issues with how I have described my question or the code please let me know. I really appreciate any advice.

```
library(terra)
library(landscapemetrics)
library(sf)
library(dplyr)

r <- rast(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), 
                    size = ncell(r),
                    replace = T)

x1 <- c(-100, -75, 0, -100) 
y1 <- c(-50, -45, 50, 50)
x2 <- c(50, 75, 100, 58) 
y2 <- c(-15, -45, 25, 10)  
p  <- vect(cbind(x1,y1), type="polygons", crs="+proj=moll")
p1 <- vect(cbind(x2,y2), type="polygons", crs="+proj=moll")

p2 <- union(p,p1)

# Running using a SpatVector
test <- sample_lsm(r, y = p2, level = "class", what = c("lsm_c_pland","lsm_c_ca", "lsm_c_area_mn"),  all_classes = T,  verbose = FALSE) 
# Error: argument "size" is missing, with no default

test <- sample_lsm(r, y = p2, size = 0, level = "class", what = c("lsm_c_pland","lsm_c_ca", "lsm_c_area_mn"),  all_classes = T,  verbose = FALSE) 
# Error: Please provide only one value as size argument (size > 0).

# Convert to sf
p2 <- st_as_sf(p2)

test <- sample_lsm(r, y = p2, size = 0, level = "class", what = c("lsm_c_pland","lsm_c_ca", "lsm_c_area_mn"),  all_classes = T,  verbose = FALSE) 

# Creating a single metric across the multiple polygons
output <- test%>% 
  pivot_wider(
    names_from = "metric", 
    values_from = "value"
  ) %>% 
  group_by(plot_id) %>% 
  mutate(total = sum(ca, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(totaltotal = sum(unique(total)))%>%
  mutate(weights = total/totaltotal)%>%
  mutate(across(c(7,9), ~.x*weights))%>%
  group_by(class)

output2 <- output%>%
  summarise(across(c(6,8), ~mean(.x,na.rm = TRUE)))

output2
```

**Comment by Nowosad** [comment]
Hi @MikeDTaylor:

1. {landscapemetrics} does not have support for *SpatVector*s (yet). We plan to move from {raster} to {terra} sometime in the future and then we should also add the *SpatVector* support.
2. I do not think we have anything built-in suitable for your use case. However, your issue got me thinking about how the `sample_lsm()` function works (see the next message).

**Comment by Nowosad** [comment]
@mhesselbarth @bitbacchus -- why do we split multipolygons to polygons before doing the sample calculations -- https://github.com/r-spatialecology/landscapemetrics/blob/acd3fd6dffa1908a8afb3cfaa5341cc50054e1ae/R/sample_lsm.R#L150

?

``` r
library(terra)
library(landscapemetrics)
library(sf)
library(dplyr)
library(tidyr)

# prepare example data ----------------------------------------------------
r <- rast(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), size = ncell(r), replace = TRUE)
x1 <- c(-100, -75, 0, -100); y1 <- c(-50, -45, 50, 50)
x2 <- c(50, 75, 100, 58); y2 <- c(-15, -45, 25, 10)  
p  <- vect(cbind(x1,y1), type = "polygons", crs = "+proj=moll")
p1 <- vect(cbind(x2,y2), type = "polygons", crs = "+proj=moll")
p2 <- terra::union(p,p1)

# convert to sf MULTIPOLYGON ----------------------------------------------
p2 <- st_as_sf(p2)
p2$id <- c(1, 1)
p3 <- p2 %>% 
  group_by(id) %>% 
  summarise()

nrow(p3) #only one feature
#> [1] 1
plot(st_geometry(p3))
```

![](https://i.imgur.com/EuHbgs3.png)

``` r
# calculate metrics -------------------------------------------------------
test <- sample_lsm(r, y = p3, size = 0, level = "class", 
                   what = c("lsm_c_pland", "lsm_c_ca", "lsm_c_area_mn"),
                   all_classes = TRUE,  verbose = FALSE) 
test
#> # A tibble: 18 × 8
#>    layer level class    id metric    value plot_id percentage_inside
#>    <int> <chr> <dbl> <int> <chr>     <dbl>   <int>             <dbl>
#>  1     1 class     1    NA area_mn  0.015        1              99.1
#>  2     1 class     2    NA area_mn  0.0233       1              99.1
#>  3     1 class     3    NA area_mn  0.035        1              99.1
#>  4     1 class     1    NA ca       0.03         1              99.1
#>  5     1 class     2    NA ca       0.07         1              99.1
#>  6     1 class     3    NA ca       0.07         1              99.1
#>  7     1 class     1    NA pland   17.6          1              99.1
#>  8     1 class     2    NA pland   41.2          1              99.1
#>  9     1 class     3    NA pland   41.2          1              99.1
#> 10     1 class     1    NA area_mn  0.0467       2             102. 
#> 11     1 class     2    NA area_mn  0.0233       2             102. 
#> 12     1 class     3    NA area_mn  0.4          2             102. 
#> 13     1 class     1    NA ca       0.14         2             102. 
#> 14     1 class     2    NA ca       0.07         2             102. 
#> 15     1 class     3    NA ca       0.4          2             102. 
#> 16     1 class     1    NA pland   23.0          2             102. 
#> 17     1 class     2    NA pland   11.5          2             102. 
#> 18     1 class     3    NA pland   65.6          2             102.
```

<sup>Created on 2022-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by MikeDTaylor** [comment]
Thanks for the swift response @Nowosad! 

>1.  {landscapemetrics} does not have support for SpatVectors (yet). We plan to move from {raster} to {terra} sometime in the future and then we should also add the SpatVector support.

I thought that was the case with {terra}, I am trying to migrate to {terra} at the moment and it has been pretty good so far.

> 2. I do not think we have anything built-in suitable for your use case. 

No worries, it is nice to know I have not missed an obvious step. Also if you had any advice on a better method to adjust the current outputs to weight and combine the metrics that would be greatly appreciated!

> why do we split multipolygons to polygons before doing the sample calculations 

If I were to uninstall {rgeos} (probably not recommended) would this remove the disaggregation that you referenced and just return a warning or would this throw up issues elsewhere?

https://github.com/r-spatialecology/landscapemetrics/blob/acd3fd6dffa1908a8afb3cfaa5341cc50054e1ae/R/sample_lsm.R#L157

**Comment by Nowosad** [comment]
@MikeDTaylor -- I commented out the disaggregation line of code and rerun the calculations -- it seems to work as you want it to... 

However, to made any changes to the code I want to wait for @mhesselbarth and @bitbacchus opinions.


``` r
library(terra)
devtools::load_all("~/Software/landscapemetrics/")
#> ℹ Loading landscapemetrics
library(sf)
library(dplyr)
library(tidyr)

# prepare example data ----------------------------------------------------
r <- rast(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), size = ncell(r), replace = TRUE)
x1 <- c(-100, -75, 0, -100); y1 <- c(-50, -45, 50, 50)
x2 <- c(50, 75, 100, 58); y2 <- c(-15, -45, 25, 10)  
p  <- vect(cbind(x1,y1), type = "polygons", crs = "+proj=moll")
p1 <- vect(cbind(x2,y2), type = "polygons", crs = "+proj=moll")
p2 <- terra::union(p,p1)

# convert to sf MULTIPOLYGON ----------------------------------------------
p2 <- st_as_sf(p2)
p2$id <- c(1, 1)
p3 <- p2 %>% 
    group_by(id) %>% 
    summarise()

test <- sample_lsm(r, y = p3, size = 0, level = "class", 
                   what = c("lsm_c_pland", "lsm_c_ca", "lsm_c_area_mn"),
                   all_classes = TRUE,  verbose = FALSE) 
test
#> # A tibble: 9 × 8
#>   layer level class    id metric    value plot_id percentage_inside
#>   <int> <chr> <dbl> <int> <chr>     <dbl>   <int>             <dbl>
#> 1     1 class     1    NA area_mn  0.0175       1              101.
#> 2     1 class     2    NA area_mn  0.022        1              101.
#> 3     1 class     3    NA area_mn  0.092        1              101.
#> 4     1 class     1    NA ca       0.21         1              101.
#> 5     1 class     2    NA ca       0.11         1              101.
#> 6     1 class     3    NA ca       0.46         1              101.
#> 7     1 class     1    NA pland   26.9          1              101.
#> 8     1 class     2    NA pland   14.1          1              101.
#> 9     1 class     3    NA pland   59.0          1              101.
```

<sup>Created on 2022-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bitbacchus** [comment]
> However, to made any changes to the code I want to wait for @mhesselbarth and @bitbacchus opinions.

I didn't work on this function, I have no idea why we use disaggregation... But testthat doesn't complain w/o either. Which might only mean we are missing a test there ;-)

**Comment by MikeDTaylor** [comment]
That sounds promising @Nowosad! This may be a silly question, but how can I replicate that without waiting for the package to potentially be updated?

I tried copying the _sample_lsm_ code and creating an alternate function with this code based out. However, this causes an error:
 >could not find function "lsm_l_ta_calc"

 I imagine I am doing something that prevents this customised version of the _sample_lsm_ function from communicating with the rest of the {landscapemetrics} functions.

**Comment by MikeDTaylor** [comment]
No worries, I have managed to create a local version of {landscapemetrics} where I could change the function and keep the dependencies. I will keep an eye out to see if disaggregation is removed from the package or an option is added.

**Comment by Nowosad** [comment]
@MikeDTaylor good to hear that you was able use your local version. Just in case, I also created a branch that you can use in the future -- `remotes::install_github("r-spatialecology/landscapemetrics@nodis")`.

**Comment by mhesselbarth** [comment]
Why did we do this? I can't really tell and remember our reasoning. I assume, we thought that most people would be interested in "sampling" each dissagregated polygon ?

**Comment by Nowosad** [comment]
Yep -- that would be my assumption as well. We probably should make a breaking change sometime in the future to allow the distinction between polygons and multipolygons.

**Comment by Nowosad** [comment]
@mhesselbarth should we make this change (removing `y <- sp::disaggregate(y)`) in our main codebase?

**Comment by mhesselbarth** [comment]
But this wouldn't allow to sample disaggregated polygons at all, correct? Maybe we could wrap this into an if else option?

**Comment by Nowosad** [comment]
Then it would depend on the input geometry type. If the input has 7 POLYGONS, you will get 7 values as the result. But if the input is one MULTIPOLYGON with 7 polygons, you will get 1 value ast the result. At least that is my thinking.

**Comment by mhesselbarth** [comment]
Oh okay, that makes sense. I think I would like that 👍

**Comment by Nowosad** [comment]
@mhesselbarth See the results using `remotes::install_github("r-spatialecology/landscapemetrics@nodis")`:

``` r
library(terra)
library(landscapemetrics)
library(sf)
library(dplyr)
library(tidyr)

# prepare example data ----------------------------------------------------
r <- rast(res = 10, crs = "+proj=moll")
values(r) <- sample(x = c(1, 2, 3, 3, 3), size = ncell(r), replace = TRUE)
x1 <- c(-100, -75, 0, -100); y1 <- c(-50, -45, 50, 50)
x2 <- c(50, 75, 100, 58); y2 <- c(-15, -45, 25, 10)  
p  <- vect(cbind(x1,y1), type = "polygons", crs = "+proj=moll")
p1 <- vect(cbind(x2,y2), type = "polygons", crs = "+proj=moll")
p2 <- terra::union(p,p1)

# convert to sf MULTIPOLYGON ----------------------------------------------
p2 <- st_as_sf(p2)
p2$id <- c(1, 1)
p3 <- p2 %>% 
  group_by(id) %>% 
  summarise()

# POLYGON test ------------------------------------------------------------
nrow(p2)
#> [1] 2
as.character(st_geometry_type(p2, by_geometry = FALSE))
#> [1] "POLYGON"
test <- sample_lsm(r, y = p2, size = 0, level = "class", 
                   what = "lsm_c_pland",
                   all_classes = TRUE,  verbose = FALSE) 
test
#> # A tibble: 6 × 8
#>   layer level class    id metric value plot_id percentage_inside
#>   <int> <chr> <dbl> <int> <chr>  <dbl>   <int>             <dbl>
#> 1     1 class     1    NA pland  23.0        1             102. 
#> 2     1 class     2    NA pland  19.7        1             102. 
#> 3     1 class     3    NA pland  57.4        1             102. 
#> 4     1 class     1    NA pland  35.3        2              99.1
#> 5     1 class     2    NA pland   5.88       2              99.1
#> 6     1 class     3    NA pland  58.8        2              99.1


# MULTIPOLYGON test -------------------------------------------------------
nrow(p3)
#> [1] 1
as.character(st_geometry_type(p3, by_geometry = FALSE))
#> [1] "MULTIPOLYGON"
test2 <- sample_lsm(r, y = p3, size = 0, level = "class", 
                   what = "lsm_c_pland",
                   all_classes = TRUE,  verbose = FALSE) 
test2
#> # A tibble: 3 × 8
#>   layer level class    id metric value plot_id percentage_inside
#>   <int> <chr> <dbl> <int> <chr>  <dbl>   <int>             <dbl>
#> 1     1 class     1    NA pland   25.6       1              101.
#> 2     1 class     2    NA pland   16.7       1              101.
#> 3     1 class     3    NA pland   57.7       1              101.
```

<sup>Created on 2022-10-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Nowosad** [comment]
@mhesselbarth maybe we can remove this disaggregation in landscapemetrics v2?

**Comment by mhesselbarth** [comment]
Yeah I think I agree. As already said in #245, I want to rework the entire `sf` support and sampling a little bit. I think it got more complicated than needed.
