### ISSUE TITLE
export layer of core areas

### ISSUE THREAD

**Issue by zuranojp** [r-spatialecology/landscapemetrics#262]
Hi folks,  could you help me to export as raster the core areas showed with "show_core" function. I have use spatialize function, but this show the core area of a patch without the cores boundary.  

thank Juan

**Comment by mhesselbarth** [comment]
Have a look at `get_boundaries`, I think thats what you are looking for...

``` r
library(landscapemetrics)
library(terra)
#> terra 1.6.7

class_1 <- get_patches(landscape, class = 1)[[1]]

boundaries <- get_boundaries(class_1)

plot(boundaries[[1]], col = c("#6ad5e8", "#a62f00"))
```

![](https://i.imgur.com/z9xfWHC.png)

<sup>Created on 2022-08-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
