### ISSUE TITLE
Percentage_inside column shows some values ​far from 100%

### ISSUE THREAD

**Issue by Leftraruu** [r-spatialecology/landscapemetrics#264]
I am trying to get the landscape metrics corresponding to a set of firescars, using a landcover raster and a firescar shape. The total wildfire data set encompasses around 1,000 fire scars, represented by polygons obtained through Google Earth Engine. When calculating the metrics, several polygons with values ​​far from 100% appear in the percentage_inside column. Searching I found this:

 _The size of the actual sampled landscape in %. It is not always 100% due to two reasons: (i) Clipping raster cells using a buffer not directly intersecting a raster cell center lead to inaccuracies and (ii) Sample plots can exceed the landscape boundary_

In this case I think it is something related to the first reason. Is there any way I can fix this in R or Arcgis? or should I just skip these polygons and just keep those with values ​​closer to 100%?
Thanks in advance!

(in the example a firescar is shown with 75%, but I have others with even lower values)
![ejemploforo](https://user-images.githubusercontent.com/114012103/191313226-64179a82-261a-4c7d-8abc-504604a724f0.png)

**Comment by mhesselbarth** [comment]
I think there is not really a way we can change that unfortunately. So I would suggest to skip the ones that are too far off from 100%

**Comment by Leftraruu** [comment]
@mhesselbarth I think I'll do that u.u, thanks for answering Max
