### ISSUE TITLE
Hectare/Metrics

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapemetrics#27]
This came up in the [testing issue](https://github.com/marcosci/landscapemetrics/issues/12):

Hectare vs map units.
Fragstats uses hectare and assumes everything you put into fragstats is in meters and has a resolution > 0.0001. We are obviously not limited by that and could use map units instead. Nevertheless, from the reproducibility and science perspective, one would lose the capability to compare results against fragstats ... but would have much more intuitive results. 

Option 1: We leave it as it right now (assuming resolution/grain in meters) and if people use the package and find it weird we change it into map units.

Option 2: They are better reasons for switching to map units than we can come up with. If so, I am happy to change everything to work with map insteads instead of hectare.

**Comment by marcosci** [comment]
It would just be another unit for the spatial scale, wouldn't it?

Anyways, you are for leaving at is and make the warning more prominent in the readme?
I am just not a big fan of implementing warnings everywhere and check for the projection.

**Comment by Nowosad** [comment]
No, It would not be. Area of e.g. 1 sq km is always (relatively) stable. However 1 sq degree (sic) is different near the equator and near to the poles... (https://www.stuffintheair.com/images/World_Map.png)

**Comment by marcosci** [comment]
That's why one always needs an expert in the group - makes perfect sense, I am total map dummy ...

**Comment by Nowosad** [comment]
Teamwork FTW.
