### ISSUE TITLE
save show_x as a raster file

### ISSUE THREAD

**Issue by carcak** [r-spatialecology/landscapemetrics#272]
Hello, 
I was wondering if there is a way to save the results of the show_x function, for example show_cores, as a georeferenced tif raster file? 

Thanks!

**Comment by mhesselbarth** [comment]
Hey, 

Have a look at `get_patches()`, I think that is what you are looking for...

**Comment by carcak** [comment]
Thank you, 
Well, That will let me save it as a raster, but it only shows me the patches> However, if I want to save as a georeferenced tiff file the same result I get from "show_cores", i.e, the core area of the patches, how could I implement that with get_patches?

**Comment by mhesselbarth** [comment]
Oh, I missed that you are only interested in the core areas. In this case, you can combine `get_patches()` to get all patches of a certain class and then `get_boundaries()` to label edge and core cells. 

Alternatively, `spatialize_lsm()` might be interesting for you.

**Comment by carcak** [comment]
Thank you very much! 
Any idea of how I could do a similar thing for "show_lsm"?

**Comment by mhesselbarth** [comment]
Thats what `spatialize_lsm()` is for

**Comment by carcak** [comment]
Great! Thank you!

**Comment by mhesselbarth** [comment]
Please re-open if you have further questions but will close for now.
