### ISSUE TITLE
Evenness metric returns NA in moving window

### ISSUE THREAD

**Issue by filippo-ferrario** [r-spatialecology/landscapemetrics#274]
# Evenness metric returns NA in moving window

When using moving windows to calculate the Shannon’s Evenness metric on a landscape using `lsm_l_shei` in `window_lsm`,
there seems to be a bug for which, when the moving window is entirely included in just one patch, the result is NA instead of 0.

``` r
library(raster)
#> Loading required package: sp
#> Warning: package 'sp' was built under R version 4.1.3
library(landscapemetrics)
#> Warning: package 'landscapemetrics' was built under R version 4.1.3


# ===================
# create raster
# ===================

r1<-raster(xmn=594124,xmx=594145,ymn=5461881,ymx=5461902, res=1, crs='+proj=utm +zone=19 +datum=WGS84 +units=m +no_defs +type=crs')
```

create the patch 1

``` r
r1[10:12,10:12]<-1  
pol_patch1<-rasterToPolygons(r1) # polygonized for later plotting
# plot(pol_patch1)
```

create the background patch

``` r
r1[is.na(r1[])]<-2  
plot(r1)
```

![](https://i.imgur.com/TCnnvIS.png)

# Apply Evenness with moving window

First, let’s create the circular and squared moving windows

``` r
# create a circular window
mw<-raster::focalWeight(r1, d=2, type=c('circle'), fillNA=T)
mw<-ifelse(mw>0,1,NA)
mw
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]   NA   NA    1   NA   NA
#> [2,]   NA    1    1    1   NA
#> [3,]    1    1    1    1    1
#> [4,]   NA    1    1    1   NA
#> [5,]   NA   NA    1   NA   NA

# create a squared window
sq<-matrix(1, ncol=5,nrow=5)
sq
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,]    1    1    1    1    1
#> [2,]    1    1    1    1    1
#> [3,]    1    1    1    1    1
#> [4,]    1    1    1    1    1
#> [5,]    1    1    1    1    1
```

Then, let’s calculate the metric

``` r
res_circ<-window_lsm(r1, what=c('lsm_l_shei'), window=mw, progress=F)
res_sq<-window_lsm(r1, what=c('lsm_l_shei'), window=sq, progress=F)

even_circ<-res_circ$layer_1$lsm_l_shei
even_sq<-res_sq$layer_1$lsm_l_shei
```

Now plot it to visualize the result

``` r
par(mfrow=c(1,2))

plot(even_circ, main='Evennes', colNA=1)
plot(pol_patch1, add=T)
text(even_circ, digits=3, cex=0.5)

plot(even_sq, main='Evennes', colNA=1)
plot(pol_patch1, add=T)
text(even_sq, digits=3, cex=0.5)
```

![](https://i.imgur.com/p5ugMqg.png)

# PROBLEM

The Evenness should not have NAs!  
Infact the Evenness should be 0 when the moving window is entirely falling on the background patch.

*Double check*  
Let’s use a smaller moving window so that even it will entirely fall whithin the patch 1

``` r
# create a circular window equivalent to a pixel 
mw1<-raster::focalWeight(r1, d=1, type=c('circle'), fillNA=T)
mw1<-ifelse(mw1>0,1,NA)
mw1
#>      [,1] [,2] [,3]
#> [1,]   NA    1   NA
#> [2,]    1    1    1
#> [3,]   NA    1   NA

small_circ<-window_lsm(r1, what=c('lsm_l_shei'), window=mw1, progress=F)
even_small_circ<-small_circ$layer_1$lsm_l_shei

plot(even_small_circ, main='Evennes', colNA=1)
```

![](https://i.imgur.com/E8syC8L.png)

the problem is confirmed.

<sup>Created on 2022-12-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
Thanks @filippo-ferrario. I think the issue can be simplified a bit. See:
``` r
library(raster)
#> Loading required package: sp
library(landscapemetrics)
r1 = raster(xmn = 594124,
            xmx = 594145,
            ymn = 5461881,
            ymx = 5461902,
            res = 1,
            crs = 'EPSG:32719')

r1[] = 1
plot(r1)
```

![](https://i.imgur.com/T4LWj0W.png)

``` r
lsm_l_shei(r1)
#> # A tibble: 1 × 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA shei     NaN
```

`NaN` is returned if there is only one class in a raster. I assume this results is due to the calculation below (based on the SHEI equation):

``` r
p = 1
m = 1
(-sum(p*log(p))) / log(m)
#> [1] NaN
```

The question (@mhesselbarth) is: should we replace NaN with 0 in these cases?

**Comment by filippo-ferrario** [comment]
Yes I think the value to be returned in such a case is 0.

Indeed, this is the behaviour that is expected also according to the `?landscapemetrics::lsm_l_shei`

> Range
0 <= SHEI < 1
> 
> Behaviour
Equals SHEI = 0 when only one patch present and equals SHEI = 1 when the proportion of classes is completely equally distributed

**Comment by Nowosad** [comment]
@mhesselbarth -- please confirm that I can change `NA` to 0 in this case.

**Comment by mhesselbarth** [comment]
I think so, yes.

**Comment by Nowosad** [comment]
@mhesselbarth see https://github.com/r-spatialecology/landscapemetrics/pull/276

``` r
library(raster)
#> Loading required package: sp
library(landscapemetrics)
r1 = raster(xmn = 594124,
            xmx = 594145,
            ymn = 5461881,
            ymx = 5461902,
            res = 1,
            crs = 'EPSG:32719')

r1[] = 1
plot(r1)
```

![](https://i.imgur.com/wsNy1WN.png)

``` r
lsm_l_shei(r1)
#> # A tibble: 1 × 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA shei       0
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
