### ISSUE TITLE
comparing_tools.Rmd

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#287]
The `comparing_tools.Rmd` vignette is not working correctly: FRAGSTATS and landscapemetrics have different number of rows...

**Comment by mhesselbarth** [comment]
Yes, we need to recalculate the FRAGSTATS results. I needed to recreate the `landscape` and something in `NLMR` or one of the dependencies changed. So the landscape is slightly different

**Comment by Nowosad** [comment]
Ok. Cannot we just go back to the previous `landscape`? What was the problem with it?

**Comment by mhesselbarth** [comment]
Yeah...Its a bit annoying right now I must admit, but I think it would be nice to be able to have a script re-producing it

**Comment by mhesselbarth** [comment]
Results are calculated but in a slightly different format. I need to update the vignettes code.

**Comment by mhesselbarth** [comment]
Related to #294

**Comment by Nowosad** [comment]
Superseded by #294
