### ISSUE TITLE
Calculating enn_mn between 2 classes instead of 1

### ISSUE THREAD

**Issue by cabuelow** [r-spatialecology/landscapemetrics#290]
Hello,

I'd like to calculate the landscape-level enn_mn metric between patches of two different classes, instead of between patches of the same class. Would this be possible to implement? 

Many thanks in advance for the help, I appreciate it.

Cheers,
Christina

**Comment by mhesselbarth** [comment]
Oh I forgot to answer here. Currently that is not implemented and thinking about it, I also dont think we will. This would take some extensive changes to the code, sorry.
