### ISSUE TITLE
print version of landscapemetrics

### ISSUE THREAD

**Issue by jszhao** [r-spatialecology/landscapemetrics#291]
Hi there,

I hope to see the version of landscapemetrics when loading it into R.
```
library(landscapemetrics)
```

By the way, `citation("landscapemetrics")` also does not report the version of landscapemetrics. It just print message something like:
`substituting the version of the application that you used for ‘v0.0’`

**Comment by mhesselbarth** [comment]
You can run `sessionInfo()` after loading the package

**Comment by Nowosad** [comment]
You can also use `packageVersion("landscapemetrics")`. 

Personally, I do not like to have many messages shown when loading packages...

**Comment by jszhao** [comment]
Thanks for the `packageVersion`.
