### ISSUE TITLE
Difference to new FRAGSTATS version

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#294]
I rerun the results using the latest FRAGSTATS version and created a test (`helper-fragstats.R`,  `test-fragstats.R`). Most metrics are identical or within a certain threshold due to numerical differences (less than 5%). However, especially DCORE is really off and I don't know why yet. Especially since most other core metrics seem to be okay. 

Also, there are a few differences of the CV or SD values on class level (more than 5% less than 10%) that I am not sure why.

**Comment by Nowosad** [comment]
Maybe gyrate difference is explained here -- https://r-spatialecology.github.io/landscapemetrics/articles/comparing_tools.html

**Comment by mhesselbarth** [comment]
Fixed vignette 7b68e22a114f35e387c632d05c0d754f3eb68d66

**Comment by mhesselbarth** [comment]
Thanks, but I start to doubt we can match the exact FRAGSTATS labelling. They are actually going zick-zack I think. Additionally, they are going by patch first and class second, where we go by class first and patch second...

**Comment by mhesselbarth** [comment]
All tests run with a correlation of p>= 0.975 on patch level and deviations of less than 5% on class and landscape level
