### ISSUE TITLE
error with raster-dev

### ISSUE THREAD

**Issue by rhijmans** [r-spatialecology/landscapemetrics#297]
When checking landscapemetrics with the dev version of "raster" (https://github.com/rspatial/raster) I now get

```
  > test_check("landscapemetrics")
  [ FAIL 1 | WARN 15 | SKIP 4 | PASS 1899 ]
  
  ══ Skipped tests (4) ═══════════════════════════════════════════════════════════
  • On CRAN (4): 'test-scale-window.R:8:5', 'test-scale-window.R:26:5',
    'test-scale-window.R:42:5', 'test-scale-window.R:75:5'
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-spatialize-lsm.R:40:5'): spatialize_lsm returns CRS ──────────
  raster::projection(result[[1]][[1]]) not equal to raster::projection(podlasie_ccilc).
  1/1 mismatches
  x[1]: "+proj=longlat +datum=WGS84 +no_defs"
  y[1]: "+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs"
  
  [ FAIL 1 | WARN 15 | SKIP 4 | PASS 1899 ]
  Error: Test failures
  Execution halted
```

This is due to changes in "raster" related to the changes in the "sp family" packages. I did not look into the details for this particular error, but comparing CRSs is always, but now more so. `sp::identicalCRS` does not work well with Raster* objects anymore.  You may want to "CRS(Raster*)" before comparing, or terra::same.crs(x, y).

I know you are going to remove support for raster anyway (thank you), so perhaps you can for now suppress this test?

**Comment by mhesselbarth** [comment]
Thanks for pointing out the error and already having a solution for it. As you said, we will remove the `raster` support soon and in fact are done with our transition to `terra`. 

So I think the easiest would be to skip the test on CRAN given we will push the new update supporting `terra` this summer anyhow. What are you thinking @Nowosad

**Comment by mhesselbarth** [comment]
ce920dc, b20c347

**Comment by rhijmans** [comment]
That works for me and thank you for the quick action!
