### ISSUE TITLE
lsm_l_frac Range

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#301]
Received this via email

> [...] I found that the lsm_l_frac_mn () function can results in values less than 1, such as 0.97 in my case. In the help page for this function, it shows that the range of frac_mn value is > 0, which seems problematical as the range is traditionally known to be 1-2. At the same time, I also noted that in the help page for  lsm_p_frac () function, the range is shown as 1-2. I am confused and thus writing to consult why the  frac_mn value can be less than 1?  [...]

**Comment by mhesselbarth** [comment]
The user supplied landscape in WGS84 so I couldn't check with FRAGSTATS, but after re-projecting, I've got the same results as with FRAGSTATS.

**Comment by Nowosad** [comment]
Geographical CRS bites again!
