### ISSUE TITLE
r studio list_ism issue

### ISSUE THREAD

**Issue by Sm665** [r-spatialecology/landscapemetrics#330]
I want to moving window analysis, and for that I need landscape-level metrics
 but R Studio only shows patch-level metrics, not landscape-level. How will I solve the problem? 
I installed raster, sf, sp, landscapemetrics, landscapetools,  ggplot2 packages.

**Comment by mhesselbarth** [comment]
Hey, 

Thanks for your question but I am not sure I understand the issue. You can calculate landscape-level metrics using the moving window approach. 

``` r
library(landscapemetrics)
library(terra)
#> terra 1.7.78
```

``` r

# import example landscape
landscape <- terra::rast(landscape)

# # show all metrics on landscape level
# list_lsm(level = "landscape")

# define window
window <- matrix(1, nrow = 5, ncol = 5)

# calculate moving window using two landscape level metrics
res <- window_lsm(landscape, window = window, what = c("lsm_l_pr", "lsm_l_joinent"))

# plot one example result
plot(res$layer_1$lsm_l_pr)
```

![](https://i.imgur.com/OnvISuW.png)

<sup>Created on 2024-07-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by Nowosad** [comment]
If you still have a problem, please reopen this issue.

**Comment by Sm665** [comment]
res <- window_lsm(landscape, window = window, what = c("lsm_l_pr", "lsm_l_joinent"))
after ran the code i got the error-
Error in Use Method("landscape_as_list") : no applicable method for 'landscape_as_list' applied to an object of class "PackedSpatRaster

**Comment by Nowosad** [comment]
@Sm665 have you run this line beforehand: `landscape <- terra::rast(landscape)`?

**Comment by Sm665** [comment]
yes after run i got these---
> #> terra 1.7.78
> # import example landscape
> 201 < - terra::rast("Landcover_4.tif")
class       : SpatRaster 
dimensions  : 1148, 1478, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : 479265, 523605, 2606865, 2641305  (xmin, xmax, ymin, ymax)
coord. ref. : WGS 84 / UTM zone 45N (EPSG:32645) 
source(s)   : memory
varname     : Landcover_4 
name        :  Name 
min value   : FALSE 
max value   : FALSE 
> # define window
> window <- matrix(1, nrow = 5, ncol = 5)
> # calculate moving window using two landscape level metrics
> res <- window_lsm(landscape, window = window, what = c("lsm_l_pr", "lsm_l_joinent"))
Error in UseMethod("landscape_as_list") : 
  no applicable method for 'landscape_as_list' applied to an object of class "PackedSpatRaster"
> # plot one example result

**Comment by Sm665** [comment]
res <- window_lsm(landscape, window = window, what = c("lsm_l_pr", "lsm_l_joinent"))
when i replaced landscape by 201 (R directory/folder)
i got
> # calculate moving window using two landscape level metrics
> res <- window_lsm(201, window = window, what = c("lsm_l_pr", "lsm_l_joinent"))
Error: unable to find an inherited method for function ‘res’ for signature ‘x = "numeric"’

**Comment by Sm665** [comment]
I made the changes you asked for and the code is working. Thanks for the code and help.
I got the image
![Rplot](https://github.com/r-spatialecology/landscapemetrics/assets/173033619/199258c0-6e1c-4b2b-9ea0-fd6d545af928)
Can you tell me from the image how I can do such a gradient analysis.  see the image
![Gradient Analysis](https://github.com/r-spatialecology/landscapemetrics/assets/173033619/7ca479a9-be26-4a46-b3cd-58c61400a8f5)
for your understanding, I attached the paper 
[GIS based Gradient Analysis.pdf](https://github.com/user-attachments/files/16077179/GIS.based.Gradient.Analysis.pdf)

**Comment by Nowosad** [comment]
@Sm665 the GitHub issues are for bug reports and other code discussions (e.g., enchantments); there are other places to ask questions, such as https://gis.stackexchange.com/
