### ISSUE TITLE
Size limitations?

### ISSUE THREAD

**Issue by diegozarrate** [r-spatialecology/landscapemetrics#334]
I am trying to run an analysis for a regional landscape that has raster with a Size of 9886 columns and 22475 rows. It weights close to 450 MB. I have not been able to run any of the indexes as it mentions a size limitation as an error even when I am working in a computer that has a RA of 64 gigas. Is there a size limitation whitin the package?

**Comment by mhesselbarth** [comment]
Not directly, but all data must be stored in RAM. So if your landscape is too big for that it might be an issues.

**Comment by Nowosad** [comment]
> It weights close to 450 MB.

I assume that this is a size of the compressed file (e.g., GeoTIFF) -- uncompressed one can be several times larger, and then R needs to read it into its memory (sometimes with some copies).

**Comment by mhesselbarth** [comment]
One way to check would be to use `terra::inMemory(x)`, however, even if that returns `TRUE` there could be issues due to the copies that @Nowosad mentioned.

**Comment by mhesselbarth** [comment]
Will close this for now. But please reopen if needed
