### ISSUE TITLE
Landscape metrics within neighborhood of points (feature request)

### ISSUE THREAD

**Issue by mstrimas** [r-spatialecology/landscapemetrics#34]
Great package, love the interface! I see two use cases that this package doesn't directly address, which come up for me when generating habitat covariates for species distribution models:

1. Given a set of points, calculate landscape metrics within a neighborhood of each point, e.g. within a 1km buffer.
2. Given a landcover raster at fine resolution, e.g. 30m, aggregate to a coarser resolution, e.g. 1km, calculating landscape metrics within each coarse cell. Solving 1 would also address this.

In both cases, I can do this in a hacky way by clipping out a small raster around each point/raster cell center, calculating the landscape metrics, then iterating over all points/centers. However, it's not very efficient. Any chance of including a helper function to speed up and simplify this process?

**Comment by mhesselbarth** [comment]
Glad to hear you like the package, thanks 😄!

Regarding 1: We working on a small study currently doing exactly what you described. So there is a fair chance we are going to include this as a helper function in the nearer future. However, we basically clip/crop the raster area around each point (using different buffer shapes) and just loop through the clippings (so not a very sophisticated solution).

Regarding 2: Not sure if we will include this. I think there a various and quite different ways to aggregate the raster values. So this would exceed the scope of the package.  The `raster` package however includes a few function dealing with this.

**Comment by mhesselbarth** [comment]
Should be implemented in the master branch. Check out `sample_metrics()` function. You can provide sample points (either as a matrix or as sp SpatialPoints). However, it is not fully tested yet! 

In case you have any feedback, we would definitely appreciate it.

**Comment by mhesselbarth** [comment]
I just recognized I forgot to implement some options for `calculate_metrics()` (e.g. `directions`). Nevertheless, the sample function should aready work. I will fix the missing options tomorrow

**Comment by mhesselbarth** [comment]
Should be fixed

**Comment by mstrimas** [comment]
This is great, thanks for implementing that so quickly, at first look this is exactly what I was hoping for. Found that it wasn't working for SpatialPoints, and submitted a small pull request to fix. 

Only improvement I can see at the moment would be to have it work for sp and sf objects.

**Comment by marcosci** [comment]
Hi Matt, awesome, thanks a ton for fixing! 

sp should work now, shouldn't it? :) maybe we could support polygons for irregular shapes, if that makes any sense.
For sf: I think at some point we decided that `as(from_sf, "Spatial")` is probably not worth the extra dependency.

Anyways, we included you as contributor, hope that is fine :-)

**Comment by mstrimas** [comment]
sp works fine now, and that makes sense re extra dependency for sf, easy enough for the user to just call as("Spatial"). Thanks again!
