### ISSUE TITLE
Ideas for future updates

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#38]
Just a list of possible ideas for future updates. 

Maybe it makes sense to also include this list as a page on the homepage?

- [ ] Think about including `terra` at some point
- [ ] Including parallel computation (if we can somehow can controll what is happening): #87
- [ ] Make sure everything runs for large raster

**Comment by marcosci** [comment]
stars should work now :+1:

**Comment by marcosci** [comment]
show_cores() implemented, needs to be tested still.

**Comment by marcosci** [comment]
What about a function that takes a raster and a vector and performs calculate_lsm on each ID of the vector? The vector would be something like the municipalities of a state.

**Comment by mhesselbarth** [comment]
This basically corresponds to the idea that `sample_metrics()` is able to use a polygon if I understand you correctly...

**Comment by marcosci** [comment]
Coming from the last issue with RAM problems: 

What do yall think if we design a function `options_lsm()` with a memory argument, that would control where `get_patches` stores the raster? If user have limited memory, then we would set this to FALSE for example and let get_patches write it's result in a tmp folder and hence store the raster on disk, rather than in RAM. 

Would slow the package even more down, but at least that should solve this issue.

**Comment by mhesselbarth** [comment]
I like both ideas

**Comment by Nowosad** [comment]
I can work on the second idea in the next few days. Regarding the first one - I am interested in seeing some alfa version and how it would behave...

**Comment by marcosci** [comment]
OK; will give it a try later :+1:

**Comment by Nowosad** [comment]
@mhesselbarth @marcosci I've started working on the `show_info()` function -  https://github.com/r-spatialecology/landscapemetrics/commit/ac655f83157bc682dc79994637d4a27415d57765. Let me know what do you think about it and how to improve it;)

**Comment by marcosci** [comment]
Awesome @Nowosad 

I did some small changes, so that it throws some messages with hints why stuff could not work - is that fine by everyone? Was to lazy to make the check sign and cross green/red, pillar seemed to complicated :astonished: 

And I renamed it, as we used the prefix `show_` for the vis functions.

**Comment by marcosci** [comment]
Next idea:

I do **really** like the printing of tibbles at the moment (in the console). The color encoding makes it quite handy to inspect your results already at this stage.

Do you think it's worth to implement that for our printing? Have colors for the level, layer, or whatever makes sense?

**Comment by marcosci** [comment]
> Coming from the last issue with RAM problems:
> 
> What do yall think if we design a function `options_lsm()` with a memory argument, that would control where `get_patches` stores the raster? If user have limited memory, then we would set this to FALSE for example and let get_patches write it's result in a tmp folder and hence store the raster on disk, rather than in RAM.
> 
> Would slow the package even more down, but at least that should solve this issue.

@Nowosad, I just pushed a hack in the lsm_to_disk branch:

https://github.com/r-spatialecology/landscapemetrics/commit/7ca859e71ec8888ad6aa86fa58051a84d64439eb

Seems to work quite fine and if lsm_to_disk is true, it writes the connected labeling in temp files.
Did you ever work with package options (next step would be to have a lsm_option(), which sets a global variable lsm_to_disk = FALSE)? Otherwise I will look how sf does that.

**Comment by marcosci** [comment]
Ok, that was much easier than expected - works like a charm, only needs some documentation.

**Comment by marcosci** [comment]
We should at some point try out terra now and think about it :+1: 

https://github.com/rspatial/terra

**Comment by mhesselbarth** [comment]
> 
> 
> Next idea:
> 
> I do **really** like the printing of tibbles at the moment (in the console). The color encoding makes it quite handy to inspect your results already at this stage.
> 
> Do you think it's worth to implement that for our printing? Have colors for the level, layer, or whatever makes sense?

In my opinion, I don't see a big advantage for our output. I think it would rather be a bit confusing and distracting. But if you all think it helps, I won't argue against it. Just don't see the need.

**Comment by Nowosad** [comment]
I have the same opinion as Max here.

**Comment by laurajanegraham** [comment]
Because I do a lot of stuff on HPC and with multiple replicates, I find unnecessary output makes debugging problems quite tricky (it tends to swamp the output logs). So I could agree with Max and Jakub here. 

You could potentially have a `verbose = TRUE` option which is set to `FALSE` as default?

**Comment by bitbacchus** [comment]
Speaking of HPC: What do you think of built-in parallelization? For some C++ functions it could be trivial, and speed-up things for larger rasters. On the other hand, for HPC you want to have full control over how things are parallelized. We could have a global option in the packet that switches on or off, or just an option per function.

What do you think?

**Comment by mhesselbarth** [comment]
We discussed this at the beginning and agreed that we do not want any internal parallelization to be able to control everything at the highest level

**Comment by marcosci** [comment]
Which we can't for the Rcpp stuff - so trying out openmp there makes actually lot of sense :+1:

**Comment by bitbacchus** [comment]
@marcosci, I'm confused ;-) We can't (why?) but it makes a lot of sense?

I'd suggest having parallelization on the Rcpp-level wherever possible, but built-in a well-documented option to switch it off for HPC use.

**Comment by marcosci** [comment]
We can't control the Rcpp stuff at the top level as Max said.

And Laura: is there anything that prints to much? We were just discussing about coloring the printing.

**Comment by mhesselbarth** [comment]
> 
> 
> @marcosci, I'm confused ;-) We can't (why?) but it makes a lot of sense?
> 
> I'd suggest having parallelization on the Rcpp-level wherever possible, but built-in a well-documented option to switch it off for HPC use.

I don't like the idea of having built-in parallelization a lot. You need to assume that the user is not fully aware of it, forgets it or whatever, which then will lead to problems at a HPC or if the users already use functions parallel. 

Maybe we can rather write a vignette to show how to use the functions (on the highest level) in parallel.  I know that all functions could be sped up by using parallelization internally, but I'm not sure if this is worth the "danger"...

**Comment by marcosci** [comment]
Default could be off. Especially for the for loops the gain would be tremendous.

**Comment by bitbacchus** [comment]
I believe there are two main user groups:

"HPC users" 
- run metrics on lot's of rather small landscapes
- and/or run many metrics on fewer landscapes

"GIS users"
- run few selected metrics on a single large raster

For the first group, we need to give the control over parallelization to the user, whereas the second goup would gain massive benefits from built-in parallelization (at the Rcpp-level).

It would be nice to help both user groups. We could maybe have a parallelized variant of some functions like `get_boundaries` and `get_boundaries_par` where the latter is identical to the first but passes a paralleizaton argument to the internal rcpp part.

**Comment by Nowosad** [comment]
Hi @bitbacchus I like your ideas. However, my main problem is I cannot think right now of any robust R packages using parallelization for its calculations. Correct me if I am wrong.

**Comment by Nowosad** [comment]
I am definitely not against it. On contrary, I would enjoy seeing robust parallelized functions for spatial data. My only objection is about how complex would be to implement it, maintain in the future, and being accepted on CRAN (aka working on all platforms).

**Comment by marcosci** [comment]
If we find a good solution, CRAN should not be a problem:
https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#OpenMP-support

**Comment by mhesselbarth** [comment]
Do we want to include the raster-format of  `sp` in a future update as well?

**Comment by Nowosad** [comment]
I would vote against it - I just think this is not worth time to add it (and maintain it in the future). 
@mhesselbarth In my opinion, you could add a new GitHub issue with this idea and close it. If there would be someone who wants this - they can reopen the issue.

**Comment by mhesselbarth** [comment]
I opened issues for the remaining bullet points for a better overview
