### ISSUE TITLE
memory leak rcpp functions

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapemetrics#42]
For larger raster objects (starts in my case with 263169 cells - 513x513 rasters from NLMR) I get the following error:

```r
 *** caught segfault ***
address 0xab0d4c0, cause 'invalid permissions'
```
Happens for some at random times, in the case of rcpp_get_composition_vector every time.
Only appears on Scientific linux/gcc 6.3.0, not on my Ubuntu machine.

Will look into this in 2 weeks - just a reminder here.

**Comment by mhesselbarth** [comment]
This is fixed as long as GEOS > 3.5 is installed, right?

**Comment by marcosci** [comment]
Found the suspect: 

`rcpp_get_composition_vector` seems to lead to segfaults ... unfortunately not very reliable, as the problem doe not occur every time I run my scripts.

@Nowosad do you have any idea why that could happen there? The only thing related I could find was:

https://github.com/RcppCore/RcppArmadillo/issues/108

... as it indeed occurs most often for large raster.

**Comment by marcosci** [comment]
I implemented a new version here:

https://github.com/r-spatialecology/landscapemetrics/blob/threadsafe_composition/src/get_composition_vector2.cpp

... it s a bit faster even than your solution, was there any reason you did not use `Rcpp::table`?

**Comment by Nowosad** [comment]
Awesome!
The only reason I can think of right now is that I didn't know about `Rcpp:table`;)

**Comment by marcosci** [comment]
OK, I thought that you had maybe a clever reason why you weren't using it.
Should work now and give the same results as the old version.

I just did a pull request - maybe you and/or Max can have a quick look over it, as we do use get_composition_vector quite often.

**Comment by Nowosad** [comment]
I've tried it a few times - looks good. 
@marcosci Awesome change - faster and simpler code!

**Comment by mhesselbarth** [comment]
Love how we always improve stuff 1 day after we sent an update to CRAN :)

**Comment by marcosci** [comment]
nice :) we should thank Dirk Eddelbuettel for Rcpp sugar, otherwise I would still be failing around.
It's currently installing on our HPC and I do really hope it fixes the segfault errors ...

and @mhesselbarth that's just an excause to have another version coming up

**Comment by marcosci** [comment]
Just had a couple of good results coming from our HPC ... weeks of trouble finally solved :sweat_smile: 

I would close here now, but we should have a deeper look into our src folder at some point with vagrant.
