### ISSUE TITLE
Base_functions()

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#43]
I just created a new branch called `base_functions` - the idea is to subsequently replace purrr::map with the apply family (base R) and also get rid of all pipes. Both just adds dependencies we actually don't really need

**Comment by Nowosad** [comment]
And what do you plan to do with **dplyr**?

**Comment by mhesselbarth** [comment]
I would prefer to keep `dplyr`. We use it quite heavily and the alternatives would mean to recode a lot of stuff in a more complicated way. I know it imports `magrittr` again. But I would get rid of the pipes anyway. We had one example were piping broke something for large raster (can't remember where exactly).

**Comment by Nowosad** [comment]
Ok. I just asked because of this magrittr dependency.

**Comment by mhesselbarth** [comment]
I mean if you really want to keep purrr and piping I'm open to discussion :)

**Comment by Nowosad** [comment]
I fine with this idea. The only question is the performance. Have you tried to measure computation time with and without purrr/pipes?

**Comment by mhesselbarth** [comment]
No, not really...but my understanding is that pipes are generally a bit slower. But the issue we had with probably a memory issue for a long pipe for a large raster may be already a good argument ;) 

Just run a few quick benchmarks for `purrr::map` vs. `lapply()` and seems like there is basically no difference

**Comment by Nowosad** [comment]
Cool. That was my guess, but it is always better to check;)

**Comment by Nowosad** [comment]
@mhesselbarth There are still some errors. 

```
  ══ testthat results  ══════════════════════════════════════════════════════
  OK: 1450 SKIPPED: 0 FAILED: 3
  1. Error: calculate_metrics can calculate class metrics (@test-calculate-metrics.R#10) 
  2. Error: (unknown) (@test-lsm-c-pafrac.R#4) 
  3. Error: (unknown) (@test-show-correlation.R#6) 
```

**Comment by Nowosad** [comment]
```  ══ testthat results  ══════════════════════════════════════════════════════  OK: 1450 SKIPPED: 0 FAILED: 3  1. Error: calculate_metrics can calculate class metrics (@test-calculate-metrics.R#10)   2. Error: (unknown) (@test-lsm-c-pafrac.R#4)   3. Error: (unknown) (@test-show-correlation.R#6) ```

**Comment by mhesselbarth** [comment]
Give 5 minutes! I just need to push and merge

**Comment by mhesselbarth** [comment]
Everything should work now. Sorry for the mistake, forgot to push some stuff...

**Comment by Nowosad** [comment]
Perfect.
