### ISSUE TITLE
How to spatialize metrics?

### ISSUE THREAD

**Issue by bniebuhr** [r-spatialecology/landscapemetrics#53]
Hi there

I have just found out about the package and it seems great. I made some tests and it is quite fast, also. Congrats for that!
My question is whether we can spatialize metrics. For instance, if I calculate the Euclidean nearest neighbor for each patch of each class, how can I produce a map with enn values in each pixel of the patches? (something to be able to visualize it, equivalent to the show_patches function but with enn values intead of class categories ou patch identity codes). 
Is it already implemented?

Thanks,
Bernardo Niebuhr

**Comment by mhesselbarth** [comment]
Hey Bernardo, 

Glad to hear you like the packages! 

Nothing like you suggest is implemented yet. But I really like the idea a lot! So maybe this could be something we try to implement for the next update...

I think the way to go would be to join patch id of the metrics `tibble` with the `get_patches()` output and just plot everything.

**Comment by mhesselbarth** [comment]
The function is now included in the most recent GitHub version of landscapemetrics. Have a look at e.g. `show_lsm(landscape, what = "lsm_p_area")`. 

Is that what you had in mind  @bniebuhr?

**Comment by Nowosad** [comment]
Hey @mhesselbarth, shouldn't it show the area value? I think right now it shows an id instead:

``` r
library(landscapemetrics)
lsm_p_area(landscape)
#> # A tibble: 27 x 6
#>    layer level class    id metric    value
#>    <int> <chr> <int> <int> <chr>     <dbl>
#>  1     1 patch     1     1 area   0.0001  
#>  2     1 patch     1     2 area   0.0148  
#>  3     1 patch     1     3 area   0.0005  
#>  4     1 patch     1     4 area   0.0014  
#>  5     1 patch     1     5 area   0.0001  
#>  6     1 patch     1     6 area   0.0005  
#>  7     1 patch     1     7 area   0.0001  
#>  8     1 patch     1     8 area   0.0001  
#>  9     1 patch     1     9 area   0.000300
#> 10     1 patch     2    10 area   0.0035  
#> # ... with 17 more rows
show_lsm(landscape, "lsm_p_area")
```

![](https://i.imgur.com/UPzkikW.png)

<sup>Created on 2018-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by bniebuhr** [comment]
Hi guys,

thanks for this update. I was thinking about something like that, indeed. I think about two applications of that:
- first, the visualization;
- second, the extraction of metrics values for given locations.

Regarding the first one, one remark here:

> The area value (or any other patch metric) is the colour fill, the label is still the patch id. I think this way its the most meanigful. Now, its easy to see that patch 25 is the largest with an area of ~0.04-0.05 ha. If the label would be the value, you wouldn't know which patch is which...
>
> But if this doesn't make sense, maybe we could add an argument if the label should be the patch id or the value?

I think it makes sense, and it is nice because the patch id informaiton is complemented by the patch area information (or any other metric). However, some times it may be difficult to infer the metric value from the color (mainly when there is too much variation, for instance, patch area metric in a landscape that is composed by patches from very small ~ some pixels ~ to very large sizes ~ thousands/millions of pixels).
Therefore I think it would be very useful to include an option to show the metric value within the pixels.

The second point arises when one has location points (for instance, occurrence of species) and wants to extract the metrics values to those points. If we have a spatially explicit map/matrix with the metrics values, it would be easy to extract its values from something like `extract(landscape, points)`. 
Do you have other solution for that, that I am still not aware? (since this is one of the most common issues in landscape ecology).

Thanks,
Bernardo

**Comment by marcosci** [comment]
Thanks for the feedback! We will include your comment for the visualization, makes a lot of sense.

The extract is already implemented, have a look at `extract_lsm`.

**Comment by mhesselbarth** [comment]
You can now set `label_lsm = TRUE` to use the value of the landscape metric as label (see a757cc5a). Because the space within each cell to put the label is limited, I rounded the results to 2 digits. However, this might be problematic because really small values (e.g. for area) getting 0.

**Comment by marcosci** [comment]
> > The extract is already implemented, have a look at `extract_lsm`.
> 
> Great, I'll take a look at that!
> Is that already described in the manual/vignette?
> I didn't find it, it would be great to find that there!

I did start that here, but lacked the time so far to explain the use case:

https://r-spatialecology.github.io/landscapemetrics/articles/articles/guide_sample_lsm.html

The idea would be to show `extract_lsm` and `sample_lsm` - as both function are often used in ecology.
`extract_lsm` takes points and gives you the landscape metric at this point, and `sample_lsm` buffers your points and gives a landscape metric for the raster values in this buffer.

If you have a good example, just point me in the right directions :+1:

**Comment by mhesselbarth** [comment]
Sadly, no - we still need to update the vignettes. But you can have a look at the example of the function 

``` 
library(landscapemetrics)
library(raster)

points <- matrix(c(10, 5, 25, 15, 5, 25), ncol = 2, byrow = TRUE)
points_sp <- sp::SpatialPoints(points)

plot(landscape)
plot(points, add = TRUE)

extract_lsm(landscape, points)
extract_lsm(landscape, points_sp, type = "area and edge metric")
```

The function returns you the landscape metric on patch level for each patch the sample points are located in. Similar to `calculate_lsm` you can specify the metrics you want.

**Comment by mhesselbarth** [comment]
Feel free to reopen anytime, but will close this for now
