### ISSUE TITLE
CRAN submission v0.3

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapemetrics#62]
We want to release the new version to CRAN at the end of the week.

Things to do:

- [x] Tests for all new functions
- [x] Sanity checks, maybe @mhesselbarth can run the use case again and I do the same with some NLMs?
- [x] Spellchecks, gp::goodpractice, etc. (e8f924d)
- [x] Update docs (https://github.com/r-spatialecology/landscapemetrics/commit/ebdf9025572c2d0636979065a7972f558e061cde)
- [x] `get_unique_values()` for `RasterStack` (cb6a1a80 / 51ff2e50)

FINAL:
- [x] Merge with CRAN branch
- [x] Create "release"-tag

**Comment by mhesselbarth** [comment]
goodpractice::gp() only returns some lines that are wider than 80 characters, which I think isn't a huge deal. Everything else is fixed (e8f924d7)

**Comment by mhesselbarth** [comment]
Just submitted v0.3 to CRAN

**Comment by mhesselbarth** [comment]
Ups...we are getting an error on the pre-tests of CRAN for Debian...Not sure why and how to reproduce and fix this at the moment

```
> # count diagonal neighbour adjacencies
> diagonal_matrix <- matrix(c(1,  NA,  1,
+                             NA,  0, NA,
+                             1,  NA,  1), 3, 3, byrow = TRUE)
> get_adjacencies(landscape, diagonal_matrix)
 ----------- FAILURE REPORT -------------- 
 --- failure: length > 1 in coercion to logical ---
 --- srcref --- 
```

**Comment by mhesselbarth** [comment]
Alright...just updated `landscapemetrics` to v0.3 on CRAN...see you for v0.4 😃
