### ISSUE TITLE
get_unique_values() does not work for vectors

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#63]
I've started writing some additional tests and found out there is an issue when a numeric/integer vector is provided to  `get_unique_values()`:

``` r
library(landscapemetrics)
get_unique_values(c(1, 3))
#> Error in UseMethod("get_unique_values"): no applicable method for 'get_unique_values' applied to an object of class "c('double', 'numeric')"
get_unique_values(c(1L, 3L))
#> Error in UseMethod("get_unique_values"): no applicable method for 'get_unique_values' applied to an object of class "c('integer', 'numeric')"
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mhesselbarth** [comment]
Did you make sured you pulled and installed the most recent version? It's working for me...

**Comment by Nowosad** [comment]
Thanks Max. You're right - I've thought that I pulled from the master branch, but there was issue with the merge...
