### ISSUE TITLE
All checks return note

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#69]
All checks started to return:

```
❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘pkgdown’
``` 

Any ideas why?

**Comment by Nowosad** [comment]
That should be a solution - https://github.com/r-spatialecology/landscapemetrics/commit/07f1830b0615d03e5919e7b54cc9f9b88380838d#diff-bc92b187c74649b3e0a039784ff93b39

**Comment by mhesselbarth** [comment]
Weird...I tried that but didn't work.  Well...whatever...thanks :) 👍
