### ISSUE TITLE
tic

### ISSUE THREAD

**Issue by marcosci** [r-spatialecology/landscapemetrics#75]
Just included a running tic script, that automatically:

- renders the readme 
- runs devtools::document
- builds the website

... if there is anything else you would like to be done by tic, let me know!
Currently, this behavior is only triggered on the master branch - so if you fork something, this will not happen there.

**Comment by Nowosad** [comment]
Great work Marco.
One thing though - is it renders the readme? It looks like .Rmd differs from .md now...

**Comment by marcosci** [comment]
Somehow the deployment script is empty on CRAN, I will investigate.

Anyways, the idea is to also move the website to a dedicated branch, should make the download from github less smaller in the future.
