### ISSUE TITLE
Getting rid of dplyr

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#76]
@marcosci and I just discussed to get rid of the `dplyr` dependency. 

Most of the time we only use `group_by()`in combination with `summarise()`which could be replaced by `aggregate()`. Besides that, we use `mutate()` here and there. But also this could be repplaced quite easily.

All of this would make our coding a bit more complicated, but maybe worth getting rid of the dependency?

Any thoughts on that ?

**Comment by bitbacchus** [comment]
maybe it's also worth checking if there is a simple solution in Rcpp available...

**Comment by Nowosad** [comment]
A summary of how we use **dplyr** is summarized below using **dplyr**:

``` r
library(dplyr)
itdepends::dep_usage_pkg("landscapemetrics") %>%
    filter(pkg == "dplyr") %>% 
    count(fun, sort = TRUE)
#> # A tibble: 11 x 2
#>    fun           n
#>    <chr>     <int>
#>  1 mutate      716
#>  2 bind_rows   688
#>  3 summarise    95
#>  4 group_by     54
#>  5 summarize    24
#>  6 case_when    13
#>  7 filter       12
#>  8 arrange       6
#>  9 select        6
#> 10 left_join     5
#> 11 if_else       1
```

<sup>Created on 2019-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mhesselbarth** [comment]
I just created a branch (no_dplyr), so we can subsequently try to remove all `dplyr` functions.

**Comment by mhesselbarth** [comment]
...and d151eea9 is the last commit removing `dplyr` completely

**Comment by mhesselbarth** [comment]
Done #78
