### ISSUE TITLE
website issues

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#83]
I was looking for one example on the package website and found out a few issues:
1. https://r-spatialecology.github.io/landscapemetrics/articles/articles/general-background.html - the plot of the left panel is not visible (there is only one color).
2. The second link in "More" is not working (https://r-spatialecology.github.io/landscapemetrics/articles/articles/comparing_fragstats_landscapemetrics.html)
3. (Just out of curiosity) Why the `patchwork::plot_layout()` function is needed in the example below (https://r-spatialecology.github.io/landscapemetrics/articles/articles/utility.html). Would not it be better to just have the `show_patches()`?

```r
landscape_plot  + 
  show_patches(landscape) + 
  patchwork::plot_layout(ncol = 1)
```

**Comment by marcosci** [comment]
I am going to fix this, also the plots. Just figured out how to reduce the whitespace, too.

**Comment by marcosci** [comment]
1. fixed (one of the reason we we needed to update landscapetools on CRAN)
2. fixed, at some point someone apparently changed the vignette filename.
3. changed it, should now make more sense.
