### ISSUE TITLE
assign metric value back to spatial object

### ISSUE THREAD

**Issue by wegmann** [r-spatialecology/landscapemetrics#85]
Hello,
great and needed R package. Do you plan or is it already possible to assign the patch or class metrics back to a spatial object?

I would like to create a map of patches with corresponding metric values instead of a table similar to the r.pi GRASS package.

thanks, Martin

**Comment by mhesselbarth** [comment]
Hey Martin, 

thanks for the feedback. 

If I understand you correctly, `show_lsm()`is what you are looking for. You can find some information [here](https://r-spatialecology.github.io/landscapemetrics/articles/articles/utility.html)

```
?show_lsm
show_lsm(landscape, what = "lsm_p_area")
```

**Comment by Nowosad** [comment]
It  gives me an error:

``` r
library(landscapemetrics)

a = get_lsm(landscape, what = c("lsm_p_area, lsm_p_perim"))
#> Warning: only using 'what' argument
#> Error: Please provide (at least one) patch level metrics only. To list available metrics, run list_lsm(level = 'patch').
```

<sup>Created on 2019-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mhesselbarth** [comment]
You have a typo in your code resulting in not selecting any metrics. `what` must be a vector with strings and not just one large string.

```
a = get_lsm(landscape, what = c("lsm_p_area",  "lsm_p_perim"))
```

Should we have two different error messages if  wrong metrics are selected (e.g. class level) and no metrics are selected at all (because of e.g. wrong specifications as diversity metrics on patch level)?

**Comment by Nowosad** [comment]
My mistake, I just copy-paste your example without any thinking;)

**Comment by Nowosad** [comment]
Btw is that warning necessary there?

``` r
library(landscapemetrics)

a = get_lsm(landscape, what = c("lsm_p_area", "lsm_p_perim"))
#> Warning: only using 'what' argument
a
#> [[1]]
#> [[1]]$lsm_p_area
#> class      : RasterLayer 
#> dimensions : 30, 30, 900  (nrow, ncol, ncell)
#> resolution : 1, 1  (x, y)
#> extent     : 0, 30, 0, 30  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : memory
#> names      : value 
#> values     : 1e-04, 0.0457  (min, max)
#> 
#> 
#> [[1]]$lsm_p_perim
#> class      : RasterLayer 
#> dimensions : 30, 30, 900  (nrow, ncol, ncell)
#> resolution : 1, 1  (x, y)
#> extent     : 0, 30, 0, 30  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : memory
#> names      : value 
#> values     : 4, 348  (min, max)
```

<sup>Created on 2019-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mhesselbarth** [comment]
The warning comes from `list_lsm()` because there the `what` argument kind of overwrites all other specifications, e.g. `list_lsm(level = "landscape", type = "diversity metrics", what = "lsm_p_area") only gives you the patch area.

**Comment by Nowosad** [comment]
I guessed that. Maybe a better approach would be to show this message only when some other argument than `what` is specified?

**Comment by mhesselbarth** [comment]
Good idea, shouldn't be too hard. Will look into that

**Comment by mhesselbarth** [comment]
> I guessed that. Maybe a better approach would be to show this message only when some other argument than `what` is specified?

Okay...that's actually how it was already programmed in `list_lsm()`. The problem was that the default for `get_lsm()`was `level = "patch"` which conflicted with a provided `what` argument. Should be fixed now (816bd28a)

**Comment by Nowosad** [comment]
@wegmann it this the function you are looking for?

**Comment by wegmann** [comment]
yes, thank you - I will try it out in the next days

**Comment by Nowosad** [comment]
Great! Feel free to reopen the issue if something is wrong/unexpected.
