### ISSUE TITLE
Update CRAN 1.0

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/landscapemetrics#89]
- [x] Update DESCRIPTION (Version: 1.0) (4712e337)
- [x] Update cran-comments.md (4712e337)
- [x] Update NEWS.md (4712e337)
- [x] Run R CMD check and devtools::check_win_release() and devtools::check_win_devel()
- [x] Merge with CRAN branch (#90 )
- [x] Create "release"-tag

I would like to merge with the CRAN branch and send the update to CRAN next week

**Comment by Nowosad** [comment]
I looked at  the pull request - looks good. 
I also reread all of the opened issues - are we able to add some of the missing metrics (https://github.com/r-spatialecology/landscapemetrics/issues/15) at this point?

**Comment by mhesselbarth** [comment]
Thanks for looking at the pull request! 

> I also reread all of the opened issues - are we able to add some of the missing metrics (#15) at this point?

I don't think anyone worked on that.

**Comment by mhesselbarth** [comment]
v1.0 arrived on CRAN 🎉
