### ISSUE TITLE
Bug in calculate_lsm(rast, what = c("lsm_c_ca"))?

### ISSUE THREAD

**Issue by nkaza** [r-spatialecology/landscapemetrics#92]
This is my first bug report. So apologies if I am not doing something right.

I am getting different results from 
`calculate_lsm(rast, what = c("lsm_c_ca"))`and  `lsm_c_ca(rast)`

```
> calculate_lsm(r2014, 'lsm_c_ca')
# A tibble: 1 x 6
  layer level class    id metric value
  <int> <chr> <int> <int> <chr>  <dbl>
1     1 class     1    NA ca      18.8
> lsm_c_ca(r2014)
# A tibble: 1 x 6
  layer level class    id metric  value
  <int> <chr> <int> <int> <chr>   <dbl>
1     1 class     1    NA ca     27512.
```

And I don't think the difference is the units. [Here](https://www.dropbox.com/s/po7053awwiobl6p/r2014.img?dl=0) is the raster I am using.

**Comment by mhesselbarth** [comment]
Hey, 
Thanks for the bug report - well done 👍 

Using `calculate_lsm()`, the resolution was somehow lost. Should be fixed in the development version. Simply, use `devtools::install_github("r-spatialecology/landscapemetrics")`.

```
> calculate_lsm(r2014, what = "lsm_c_ca")
# A tibble: 1 x 6
  layer level class    id metric  value
  <int> <chr> <int> <int> <chr>   <dbl>
1     1 class     1    NA ca     27512.
> lsm_c_ca(r2014)
# A tibble: 1 x 6
  layer level class    id metric  value
  <int> <chr> <int> <int> <chr>   <dbl>
1     1 class     1    NA ca     27512.
``` 

In case everything is fixed to your satisfaction, please close the issue :)

**Comment by nkaza** [comment]
Excellent. Thank you!
